export interface QuoteSeed {
  text: string;
  author: string;
}

/** Kho câu nói/châm ngôn mặc định cho widget câu nói ngẫu nhiên ở trang chủ — nguồn gốc mang qua từ dự án well-known/index.html. */
export const QUOTES_SEED: QuoteSeed[] = [
  { text: 'Cách tốt nhất để dự đoán tương lai là tự tay tạo ra nó.', author: 'Peter Drucker' },
  { text: 'Hành trình ngàn dặm bắt đầu từ một bước chân.', author: 'Lão Tử' },
  { text: 'Không bắt đầu thì chẳng bao giờ giỏi được.', author: 'Zig Ziglar' },
  { text: 'Thất bại là cơ hội bắt đầu lại, lần này khôn hơn.', author: 'Henry Ford' },
  { text: 'Hãy là sự thay đổi bạn muốn thấy.', author: 'Gandhi' },
  { text: 'Khó khăn không kéo dài mãi, người kiên cường thì có.', author: 'R. Schuller' },
  { text: 'Đừng đếm số ngày, hãy khiến mỗi ngày đáng giá.', author: 'Muhammad Ali' },
  { text: 'Cơ hội không tự đến, bạn phải tạo ra nó.', author: 'Chris Grosser' },
  { text: 'Người lạc quan thấy cơ hội trong mọi khó khăn.', author: 'Churchill' },
  { text: 'Tin rằng mình làm được, thế là đã đi nửa đường.', author: 'T. Roosevelt' },
  { text: 'Bí quyết để tiến lên là bắt đầu.', author: 'Mark Twain' },
  { text: 'Đừng sợ đi chậm, chỉ sợ đứng yên.', author: 'Tục ngữ' },
  { text: 'Bền bỉ chinh phục mọi thứ.', author: 'Benjamin Franklin' },
  { text: 'Làm điều bình thường một cách phi thường.', author: 'Khuyết danh' },
  { text: 'Giấc mơ không hết hạn, chỉ có người bỏ cuộc.', author: 'Khuyết danh' },
  { text: 'Mỗi chuyên gia đều từng là người mới bắt đầu.', author: 'Khuyết danh' },
  { text: 'Bạn không thua cho đến khi bạn ngừng cố gắng.', author: 'Khuyết danh' },
  { text: 'Áp lực tạo ra kim cương.', author: 'Khuyết danh' },
  { text: 'Gieo thói quen, gặt số phận.', author: 'Khuyết danh' },
  { text: 'Việc khó làm hôm nay, mai sẽ thành chuyện nhỏ.', author: 'Khuyết danh' },
  { text: 'Đừng chờ cảm hứng, hãy bắt tay rồi cảm hứng sẽ tới.', author: 'Khuyết danh' },
  { text: 'Kỷ luật là cây cầu nối ước mơ và hiện thực.', author: 'Jim Rohn' },
  { text: 'Bạn là trung bình của 5 người bạn dành thời gian nhiều nhất.', author: 'Jim Rohn' },
  { text: 'Tốt hơn hôm qua, đó đã là chiến thắng.', author: 'Khuyết danh' },
  { text: 'Không có gió ngược, diều chẳng thể bay cao.', author: 'Khuyết danh' },
  { text: 'Cứ đi rồi sẽ đến.', author: 'Lỗ Tấn' },
  { text: 'Thái độ quyết định độ cao.', author: 'Khuyết danh' },
  { text: 'Ngã bảy lần, đứng dậy tám lần.', author: 'Tục ngữ Nhật' },
  { text: 'Hôm nay khó, ngày mai khó hơn, nhưng ngày kia sẽ đẹp.', author: 'Jack Ma' },
  { text: 'Đừng so mình với người khác, hãy so với chính mình hôm qua.', author: 'Khuyết danh' },
  { text: 'Tôi không lười, tôi chỉ đang ở chế độ tiết kiệm pin.', author: 'Khuyết danh' },
  { text: 'Deadline là nguồn cảm hứng sáng tạo lớn nhất nhân loại.', author: 'Khuyết danh' },
  { text: 'Tôi đã giảm cân thành công… từ ví tiền.', author: 'Khuyết danh' },
  { text: 'Cà phê: vì người lớn cũng cần siêu năng lực.', author: 'Khuyết danh' },
  { text: 'Tôi không trì hoãn, tôi đang ủ ý tưởng cho chín.', author: 'Khuyết danh' },
  { text: 'Ngủ là cách thiền sâu nhất mà tôi từng thử.', author: 'Khuyết danh' },
  { text: 'Tài khoản ngân hàng của tôi cũng theo đuổi lối sống tối giản.', author: 'Khuyết danh' },
  { text: 'Tôi đa nhiệm: vừa lo lắng, vừa chẳng làm gì.', author: 'Khuyết danh' },
  { text: 'Đời cho tôi quả chanh, tôi đem… bán lại.', author: 'Khuyết danh' },
  { text: 'Tập gym mệt, nên tôi tập kiên nhẫn ở nhà.', author: 'Khuyết danh' },
  { text: 'Tôi nói được 3 thứ tiếng: tiếng mẹ đẻ, tiếng lóng và tiếng thở dài.', author: 'Khuyết danh' },
  { text: 'Kế hoạch của tôi rất chắc: không có kế hoạch nào cả.', author: 'Khuyết danh' },
  { text: 'Tôi không béo, chỉ là dễ thương theo chiều ngang.', author: 'Khuyết danh' },
  { text: 'Đừng từ bỏ ước mơ, hãy tiếp tục ngủ.', author: 'Khuyết danh' },
  { text: 'Tiền không mua được hạnh phúc, nhưng mua được trà sữa, gần như nhau.', author: 'Khuyết danh' },
  { text: 'Tôi đến phòng gym để nó biết mặt, vậy là đủ.', author: 'Khuyết danh' },
  { text: 'Năng suất của tôi tỉ lệ thuận với độ gần deadline.', author: 'Khuyết danh' },
  { text: 'Tôi rất giỏi việc bắt đầu… việc bắt đầu.', author: 'Khuyết danh' },
  { text: 'Đời là bể khổ, may là tôi biết bơi… kiểu chó.', author: 'Khuyết danh' },
  { text: 'Tôi đã tìm thấy lối thoát trong công việc: thoát vị đĩa đệm.', author: 'Khuyết danh' },
  { text: 'Người ta nói im lặng là vàng, nên tôi đang tích cóp làm giàu.', author: 'Khuyết danh' },
  { text: 'Tôi không thất nghiệp, tôi đang là CEO của thời gian rảnh.', author: 'Khuyết danh' },
  { text: 'Mỗi sáng tôi đều dậy sớm… để tắt báo thức rồi ngủ tiếp.', author: 'Khuyết danh' },
  { text: 'Tôi ăn kiêng rất nghiêm túc: kiêng… ăn ít.', author: 'Khuyết danh' },
  { text: 'Học, học nữa, học mãi — và tôi vẫn chưa học xong cách dậy sớm.', author: 'Khuyết danh' },
  { text: 'Sống là phải cho đi, nên tôi cho qua hết deadline.', author: 'Khuyết danh' },
  { text: 'Tôi không stress, tôi chỉ đang vận động nội tâm cường độ cao.', author: 'Khuyết danh' },
  { text: 'Có công mài sắt, có ngày… chai tay.', author: 'Khuyết danh' },
  { text: 'Wifi yếu mới biết ai là bạn thật.', author: 'Khuyết danh' },
  { text: 'Tôi và đồng tiền: hợp nhau lắm, gặp là chia tay.', author: 'Khuyết danh' },
  { text: 'Đi một ngày đàng, học một sàng… mỏi chân.', author: 'Khuyết danh' },
  { text: 'Tôi quyết tâm thay đổi, bắt đầu từ ngày mai. Mai nào cũng được.', author: 'Khuyết danh' },
  { text: 'Thức khuya có hại, nên tôi thức tới sáng cho an toàn.', author: 'Khuyết danh' },
  { text: 'Tôi không nghiện mua sắm, tôi đang ủng hộ nền kinh tế.', author: 'Khuyết danh' },
  { text: 'Bí quyết hạnh phúc: kỳ vọng thấp, wifi mạnh.', author: 'Khuyết danh' },
  { text: 'Một việc nhỏ hoàn thành hơn trăm việc lớn dang dở.', author: 'Khuyết danh' },
  { text: 'Bắt đầu từ nơi bạn đang đứng.', author: 'Arthur Ashe' },
  { text: 'Đừng đợi thời cơ hoàn hảo, hãy làm cho thời điểm trở nên hoàn hảo.', author: 'Khuyết danh' },
  { text: 'Sợ hãi chỉ là cảm xúc, không phải lời tiên tri.', author: 'Khuyết danh' },
  { text: 'Hãy mơ lớn, bắt đầu nhỏ, hành động ngay.', author: 'Robin Sharma' },
  { text: 'Thành công đến với người bận rộn tìm kiếm nó.', author: 'Khuyết danh' },
  { text: 'Năng lực sinh ra từ giới hạn được vượt qua.', author: 'Khuyết danh' },
  { text: 'Đừng để hôm qua chiếm chỗ của hôm nay.', author: 'Khuyết danh' },
  { text: 'Kết quả là phần thưởng cho sự kiên trì.', author: 'Khuyết danh' },
  { text: 'Mọi đỉnh núi đều có lối lên.', author: 'Khuyết danh' },
  { text: 'Hãy làm, hoặc không làm. Đừng cố thử.', author: 'Yoda' },
  { text: 'Chậm mà chắc vẫn thắng cuộc đua.', author: 'Aesop' },
  { text: 'Càng đổ mồ hôi lúc tập, càng ít đổ máu lúc thi.', author: 'Khuyết danh' },
  { text: 'Cây cối lớn lên trong im lặng.', author: 'Khuyết danh' },
  { text: 'Mỗi \'không\' đưa bạn gần hơn một \'có\'.', author: 'Khuyết danh' },
  { text: 'Việc đáng làm thì đáng làm dở lúc đầu.', author: 'G.K. Chesterton' },
  { text: 'Sự chuẩn bị là một nửa của chiến thắng.', author: 'Cervantes' },
  { text: 'Người mạnh không phải không ngã, mà là biết đứng lên.', author: 'Khuyết danh' },
  { text: 'Hãy gieo điều tử tế, rồi gặt sự bình yên.', author: 'Khuyết danh' },
  { text: 'Cuộc đời 10% là điều xảy ra, 90% là cách bạn phản ứng.', author: 'Charles Swindoll' },
  { text: 'Không ai có thể khiến bạn thấy thấp kém nếu bạn không cho phép.', author: 'E. Roosevelt' },
  { text: 'Hành động là liều thuốc giải cho nỗi sợ.', author: 'Khuyết danh' },
  { text: 'Tập trung vào tiến bộ, không phải sự hoàn hảo.', author: 'Khuyết danh' },
  { text: 'Ý tưởng không đáng giá gì nếu không thực thi.', author: 'Khuyết danh' },
  { text: 'Kiên nhẫn là sức mạnh thầm lặng.', author: 'Khuyết danh' },
  { text: 'Mỗi ngày là một trang trắng, hãy viết đẹp.', author: 'Khuyết danh' },
  { text: 'Làm điều đúng, kể cả khi không ai nhìn.', author: 'Khuyết danh' },
  { text: 'Đừng sợ đối thủ giỏi, hãy sợ chính mình lười.', author: 'Khuyết danh' },
  { text: 'Sóng to mới biết tay chèo cứng.', author: 'Tục ngữ' },
  { text: 'Học từ hôm qua, sống cho hôm nay, hy vọng cho ngày mai.', author: 'Einstein' },
  { text: 'Đừng để tiếng ồn của ý kiến người khác át đi tiếng lòng bạn.', author: 'Steve Jobs' },
  { text: 'Chất lượng không phải hành động, mà là thói quen.', author: 'Aristotle' },
  { text: 'Khởi đầu chậm không quyết định đích đến.', author: 'Khuyết danh' },
  { text: 'Năng lượng đi đâu, kết quả theo đó.', author: 'Khuyết danh' },
  { text: 'Tử tế là ngôn ngữ ai cũng hiểu.', author: 'Khuyết danh' },
  { text: 'Một bước nhỏ mỗi ngày tạo nên hành trình lớn.', author: 'Khuyết danh' },
  { text: 'Đừng so sánh chương 1 của bạn với chương 20 của người khác.', author: 'Khuyết danh' },
  { text: 'Bạn không cần thấy hết cầu thang, chỉ cần bước bậc đầu tiên.', author: 'M.L. King' },
  { text: 'Thành công là đi từ thất bại này đến thất bại khác mà không mất nhiệt huyết.', author: 'Churchill' },
  { text: 'Cuộc đời là bể khổ, qua hết bể khổ là đến bể khác!', author: 'Khuyết danh' },
  { text: 'Người ta nói mình béo, nhưng mình thấy đơn giản là mình đang tích trữ năng lượng cho tương lai thôi!', author: 'Khuyết danh' },
  { text: 'Bạn muốn người yêu ngồi đối diện hay ngồi cạnh? Tôi thích họ ngồi xung quanh.', author: 'Khuyết danh' },
  { text: 'Cách để không bị lợi dụng đó là trở nên vô dụng.', author: 'Khuyết danh' },
  { text: 'Đi tu chưa chắc thành chín quả, nhưng chơi ngu thì sẽ nhận hậu quả.', author: 'Khuyết danh' },
  { text: 'Tôi của những ngày gần đây: Độc lập, tự do, ăn no, đi ngủ.', author: 'Khuyết danh' },
  { text: 'Ở cái tuổi đáng ra phải đau khổ vì tình, thì tôi lại đau lưng.', author: 'Khuyết danh' },
  { text: 'Hôm nay gió lớn quá, vốn dĩ muốn đến phòng gym, gió lại thổi mình đến quán trà sữa.', author: 'Khuyết danh' },
  { text: 'Anh đâu phải người nhện, sao cứ thích bôi tơ.', author: 'Khuyết danh' },
  { text: 'Có những thứ mất rồi mới thấy, mất cũng được.', author: 'Khuyết danh' },
  { text: 'Đóng cửa trái tim. Đẹp trai thì mở.', author: 'Khuyết danh' },
  { text: 'Đã cố gắng đến công ty, nhưng trí óc lại quyết định ở nhà!', author: 'Khuyết danh' },
  { text: 'Khách hàng là thượng đế, nên tự nhủ: phải tinh tế, không được đánh khách hàng.', author: 'Khuyết danh' },
  { text: 'Đầu lòng hai ả tố nga. Thúy Kiều là chị, mai là thứ hai.', author: 'Khuyết danh' },
  { text: 'Deadline không dí tôi, tôi dí deadline.', author: 'Khuyết danh' },
  { text: 'Kẻ tổn thương nhất vẫn là kẻ phải chạy deadline tối thứ 7.', author: 'Khuyết danh' },
  { text: 'Nếu người khác làm được thì mình nhờ họ làm luôn.', author: 'Khuyết danh' },
  { text: 'Đã có chồng, chồng chất deadline.', author: 'Khuyết danh' },
  { text: 'Một điều nhịn là 9 đứa ngồi lên đầu.', author: 'Khuyết danh' },
  { text: 'Bằng mặt nhưng không bằng lái.', author: 'Khuyết danh' },
  { text: 'Ở đời đừng khinh thường người khác. Hôm nay tôi chưa có tiền, chắc gì ngày mai tôi đã có.', author: 'Khuyết danh' },
  { text: 'Bi kịch của đời người chính là: đam mê ẩm thực nhưng lại tích cực giảm cân.', author: 'Khuyết danh' },
  { text: 'Đi bộ còn té lên té xuống mà đòi đi cùng nhau cả đời.', author: 'Khuyết danh' },
  { text: 'Sống hướng nội nhưng hội nào cũng không thiếu mặt.', author: 'Khuyết danh' },
  { text: 'Học đi đôi với hành. Hành đi đôi với tỏi.', author: 'Khuyết danh' },
  { text: 'The sun will rise and we will try again.', author: 'Khuyết danh' },
  { text: 'Sunsets are proof that endings can be beautiful too.', author: 'Khuyết danh' },
  { text: 'Live for you, not for anyone.', author: 'Khuyết danh' },
  { text: 'Trong các loại buồn chỉ có buồn cười là vui nhất.', author: 'Khuyết danh' },
  { text: 'Giao diện trưởng thành. Nhưng hệ điều hành nhõng nhẽo.', author: 'Khuyết danh' },
  { text: 'Có một thứ tiền không mua được. Đó chính là sự nghèo khó!', author: 'Khuyết danh' },
  { text: 'Béo không phải tội mà là vượt trội về thể xác.', author: 'Khuyết danh' },
  { text: 'Trên đường đời tấp nập, ta vô tình nhặt phải xấp đô la?', author: 'Khuyết danh' },
  { text: 'Hãy tự đi lên bằng chính đôi chân của mình… nếu thang máy hỏng.', author: 'Khuyết danh' },
  { text: 'Cuộc sống vốn ngắn ngủi. Thế nên bạn hãy cười khi còn đủ răng.', author: 'Khuyết danh' },
  { text: 'Không phải vì ế mà chưa có người yêu, chẳng qua là em chưa \'come out\' giới tính thật của mình haha.', author: 'Khuyết danh' },
  { text: 'Đi một ngày đàng… rớt mất 200.000.', author: 'Khuyết danh' },
  { text: 'Hey Siri, tua về chủ nhật.', author: 'Khuyết danh' },
  { text: 'Em dành thời gian cho em đi em! Ra ngoài đường kết bạn làm điều gì đó ý nghĩa đi em.', author: 'Khuyết danh' },
  { text: 'Bóc trúng sít rịt.', author: 'Khuyết danh' },
  { text: 'Mười điểm không có nhưng.', author: 'Khuyết danh' },
  { text: 'Gwenchana.', author: 'Khuyết danh' },
  { text: 'Còn thở là còn gỡ.', author: 'Khuyết danh' },
  { text: 'Cuộc đời không phải là chờ đợi cơn bão qua đi, mà là học cách khiêu vũ dưới mưa.', author: 'Vivian Greene' },
  { text: 'Bạn không thể đi ngược chiều gió, nhưng bạn có thể điều chỉnh cánh buồm.', author: 'Jimmy Dean' },
  { text: 'Thành công không phải là chìa khóa của hạnh phúc. Hạnh phúc mới là chìa khóa của thành công.', author: 'Albert Schweitzer' },
  { text: 'Hãy là sự thay đổi mà bạn muốn thấy trên thế giới.', author: 'Mahatma Gandhi' },
  { text: 'Trong lúc khó khăn nhất, hãy nhớ rằng bầu trời sau mưa bao giờ cũng trong hơn.', author: 'Khuyết danh' },
  { text: 'Điều duy nhất ngăn bạn đạt được ước mơ là nỗi sợ rằng bạn sẽ thất bại.', author: 'Paulo Coelho' },
  { text: 'Đừng đếm những ngày, hãy làm cho những ngày đó đáng để đếm.', author: 'Muhammad Ali' },
  { text: 'Sự kiên nhẫn là đắng, nhưng quả của nó rất ngọt.', author: 'Aristotle' },
  { text: 'Cuộc hành trình ngàn dặm bắt đầu từ một bước chân.', author: 'Lão Tử' },
  { text: 'Không ai có thể làm bạn cảm thấy thấp kém nếu bạn không cho phép họ.', author: 'Eleanor Roosevelt' },
  { text: 'Điều tốt nhất bạn có thể làm là đúng. Điều tốt thứ nhì là sai. Điều tệ nhất là không làm gì cả.', author: 'Theodore Roosevelt' },
  { text: 'Hạnh phúc không phải là đích đến, mà là cách bạn đi trên đường.', author: 'Roy M. Goodman' },
  { text: 'Bạn chỉ sống một lần, nhưng nếu sống đúng cách, một lần là đủ.', author: 'Mae West' },
  { text: 'Kẻ thất bại không phải là người ngã, mà là người từ chối đứng dậy.', author: 'Mary Pickford' },
  { text: 'Đừng nói mình không có thời gian. Bạn có đúng 24 giờ như Beethoven, Michelangelo, và Leonardo da Vinci.', author: 'H. Jackson Brown Jr.' },
  { text: 'Tương lai thuộc về những ai tin vào vẻ đẹp của ước mơ.', author: 'Eleanor Roosevelt' },
  { text: 'Thành công là tổng hợp của những nỗ lực nhỏ được lặp đi lặp lại ngày này qua ngày khác.', author: 'Robert Collier' },
  { text: 'Hãy sống như thể hôm nay là ngày cuối cùng của bạn. Hãy học như thể bạn sẽ sống mãi mãi.', author: 'Mahatma Gandhi' },
  { text: 'Sự vĩ đại không phải từ trên trời rơi xuống, mà được rèn giũa qua gian khó.', author: 'Khuyết danh' },
  { text: 'Đừng chờ đến khi hoàn hảo mới bắt đầu. Bắt đầu và dần trở nên hoàn hảo.', author: 'Khuyết danh' },
  { text: 'Người thông minh nhất trong phòng là người biết rằng mình vẫn còn nhiều thứ cần học.', author: 'Khuyết danh' },
  { text: 'Mỗi chuyên gia từng là người mới bắt đầu.', author: 'Helen Hayes' },
  { text: 'Chỉ có hai ngày trong năm không thể làm được gì: hôm qua và ngày mai.', author: 'Đức Đạt Lai Lạt Ma' },
  { text: 'Bạn không cần phải vĩ đại để bắt đầu, nhưng bạn phải bắt đầu để trở nên vĩ đại.', author: 'Zig Ziglar' },
  { text: 'Sai lầm lớn nhất bạn có thể mắc là sợ mắc sai lầm.', author: 'Elbert Hubbard' },
  { text: 'Khi mọi thứ có vẻ đi ngược lại bạn, hãy nhớ rằng máy bay cất cánh ngược chiều gió, không phải xuôi chiều.', author: 'Henry Ford' },
  { text: 'Nếu bạn không xây dựng ước mơ của mình, ai đó sẽ thuê bạn xây dựng ước mơ của họ.', author: 'Tony Gaskins' },
  { text: 'Thời gian không chờ ai, hãy dùng nó trước khi nó dùng bạn.', author: 'Khuyết danh' },
  { text: 'Khó khăn chuẩn bị những người bình thường cho số phận phi thường.', author: 'C.S. Lewis' },
  { text: 'Đời không cho bạn những gì bạn muốn, mà cho bạn những gì bạn cần để trưởng thành.', author: 'Khuyết danh' },
  { text: 'Hãy yêu bản thân đủ để đặt ra ranh giới. Thời gian và năng lượng của bạn là quý giá.', author: 'Anna Taylor' },
  { text: 'Mưa không rơi mãi. Đêm không dài mãi. Khó khăn rồi cũng qua.', author: 'Khuyết danh' },
  { text: 'Người mạnh không phải là người không bao giờ khóc, mà là người khóc xong rồi đứng dậy tiếp tục.', author: 'Khuyết danh' },
  { text: 'Đừng so sánh chương một của bạn với chương hai mươi của người khác.', author: 'Khuyết danh' },
  { text: 'Sự khác biệt giữa người thành công và người không thành công không phải là sức mạnh hay kiến thức, mà là ý chí.', author: 'Vince Lombardi' },
  { text: 'Nếu bạn muốn tỏa sáng như mặt trời, trước tiên hãy cháy như mặt trời.', author: 'A.P.J. Abdul Kalam' },
  { text: 'Không có thất bại nào là cuối cùng, cũng không có thành công nào là mãi mãi. Điều quan trọng là dũng khí để tiếp tục.', author: 'Winston Churchill' },
  { text: 'Điều bạn nghĩ về bản thân quan trọng hơn nhiều so với điều người khác nghĩ về bạn.', author: 'Seneca' },
  { text: 'Hành động là nền tảng của mọi thành công.', author: 'Pablo Picasso' },
  { text: 'Cuộc đời cho bạn hai lựa chọn: chấp nhận những điều kiện tồn tại, hoặc chịu trách nhiệm thay đổi chúng.', author: 'Denis Waitley' },
  { text: 'Đừng để ngày mai nhận những gì bạn có thể làm hôm nay.', author: 'Benjamin Franklin' },
  { text: 'Sự tự tin không đến từ việc luôn đúng, mà từ việc không sợ sai.', author: 'Rosalind Russell' },
  { text: 'Học từ ngày hôm qua, sống cho hôm nay, hi vọng vào ngày mai.', author: 'Albert Einstein' },
  { text: 'Bạo lực duy nhất xứng đáng sử dụng là bạo lực dùng để tự vệ cho người yếu hơn.', author: 'Mahatma Gandhi' },
  { text: 'Thay đổi không phải lúc nào cũng dễ dàng, nhưng nó luôn xứng đáng.', author: 'Khuyết danh' },
  { text: 'Bạn không thể kiểm soát mọi thứ xảy ra với bạn, nhưng bạn có thể kiểm soát cách phản ứng.', author: 'Khuyết danh' },
  { text: 'Sức mạnh không đến từ cơ thể, mà từ ý chí không khuất phục.', author: 'Mahatma Gandhi' },
  { text: 'Mọi thứ bạn từng muốn đều nằm ở phía bên kia của nỗi sợ hãi.', author: 'George Addair' },
  { text: 'Nơi tối nhất luôn là ngay trước bình minh.', author: 'Thomas Fuller' },
  { text: 'Hãy tử tế với mọi người bạn gặp, vì mỗi người đều đang chiến đấu với một trận chiến mà bạn không biết.', author: 'Plato' },
  { text: 'Điều tốt nhất về tương lai là nó đến từng ngày một.', author: 'Abraham Lincoln' },
  { text: 'Khi bạn không thể quay lại, bạn chỉ còn cách tiến về phía trước.', author: 'Paulo Coelho' },
  { text: 'Hãy làm điều tốt hôm nay, ngay cả khi bạn không được nhớ đến vào ngày mai.', author: 'Mẹ Teresa' },
  { text: 'Cuộc sống là 10% những gì xảy ra với bạn và 90% cách bạn phản ứng.', author: 'Charles R. Swindoll' },
  { text: 'Không có ước mơ nào quá lớn, không có mơ ước nào quá nhỏ.', author: 'Khuyết danh' },
  { text: 'Người thành công không sợ mất đi những gì họ có, họ tập trung vào những gì họ có thể đạt được.', author: 'Khuyết danh' },
  { text: 'Thử thách là những gì làm cuộc sống thú vị; vượt qua chúng là điều làm cuộc sống có ý nghĩa.', author: 'Joshua J. Marine' },
  { text: 'Nếu bạn muốn hạnh phúc, hãy gắn nó với mục tiêu, không phải con người hay vật chất.', author: 'Albert Einstein' },
  { text: 'Đừng nhìn đồng hồ — hãy làm những gì nó làm. Cứ tiếp tục.', author: 'Sam Levenson' },
  { text: 'Chúng ta là những gì chúng ta liên tục làm. Vì vậy sự xuất sắc không phải là hành động, mà là thói quen.', author: 'Aristotle' },
  { text: 'Điều tệ nhất xảy ra không phải là thất bại, mà là khi bạn không cố gắng.', author: 'Khuyết danh' },
  { text: 'Hãy sống theo giá trị của bạn, không phải theo kỳ vọng của người khác.', author: 'Khuyết danh' },
  { text: 'Bạn đủ mạnh hơn những gì bạn nghĩ, thông minh hơn những gì bạn tin, và có khả năng hơn những gì bạn tưởng.', author: 'Khuyết danh' },
  { text: 'Mỗi buổi sáng là một cơ hội mới để bắt đầu lại.', author: 'Khuyết danh' },
  { text: 'Niềm tin không làm cho mọi thứ dễ dàng, nhưng nó làm cho chúng trở nên có thể.', author: 'Khuyết danh' },
  { text: 'Khi bạn cảm thấy muốn bỏ cuộc, hãy nhớ lý do tại sao bạn bắt đầu.', author: 'Khuyết danh' },
  { text: 'Hạnh phúc thực sự đến khi bạn nhận ra bạn đã có đủ.', author: 'Khuyết danh' },
  { text: 'Đừng chờ cảm hứng. Hãy hành động và cảm hứng sẽ đến sau.', author: 'Jack London' },
  { text: 'Tất cả những giấc mơ có thể trở thành sự thật, nếu chúng ta có dũng khí theo đuổi chúng.', author: 'Walt Disney' },
  { text: 'Bạn không thể trở lại và thay đổi điểm khởi đầu, nhưng bạn có thể bắt đầu nơi bạn đang đứng và thay đổi điểm kết thúc.', author: 'C.S. Lewis' },
  { text: 'Mỗi ngày là một món quà. Đó là lý do người ta gọi nó là hiện tại.', author: 'Khuyết danh' },
  { text: 'Hãy ngừng lo lắng về những gì người khác nghĩ. Hãy lo lắng về những gì bạn nghĩ về chính mình.', author: 'Khuyết danh' },
  { text: 'Đôi khi bạn cần bước ra khỏi không gian mà bạn đang đứng và nhìn lại từ một góc độ khác.', author: 'Khuyết danh' },
  { text: 'Chỉ khi đêm xuống, bạn mới thấy được những ngôi sao.', author: 'Martin Luther King Jr.' },
  { text: 'Lòng dũng cảm không phải là không có nỗi sợ, mà là nhận ra có điều gì đó quan trọng hơn nỗi sợ.', author: 'Ambrose Redmoon' },
  { text: 'Yêu thương bản thân không phải là ích kỷ — đó là điều kiện tiên quyết để yêu thương người khác.', author: 'Khuyết danh' },
  { text: 'Sự thất bại chỉ là cơ hội để bắt đầu lại, lần này thông minh hơn.', author: 'Henry Ford' },
  { text: 'Bạn không thể kéo dài ngày, nhưng bạn có thể dùng nó sâu sắc hơn.', author: 'Khuyết danh' },
  { text: 'Đời ngắn lắm — đừng dành nó để sống theo cuộc đời của người khác.', author: 'Steve Jobs' },
  { text: 'Hãy tử tế hơn mức cần thiết, vì mọi người bạn gặp đều đang chiến đấu với điều gì đó.', author: 'Khuyết danh' },
  { text: 'Thành công không đến với ai chờ đợi nó.', author: 'Jawaharlal Nehru' },
  { text: 'Bạn không thể sử dụng thời gian đã qua, nhưng bạn hoàn toàn có thể làm chủ thời gian phía trước.', author: 'Khuyết danh' },
  { text: 'Một ước mơ mà bạn không hành động để thực hiện chỉ là một giấc ngủ.', author: 'Edwin Louis Cole' },
  { text: 'Không phải những gì xảy ra với bạn định nghĩa bạn, mà là cách bạn đứng dậy sau đó.', author: 'Khuyết danh' },
  { text: 'Hãy chọn một công việc bạn yêu thích, và bạn sẽ không phải làm việc một ngày nào trong cuộc đời.', author: 'Khổng Tử' },
  { text: 'Điều bạn tập trung vào sẽ phát triển.', author: 'Khuyết danh' },
  { text: 'Đừng chờ ai cứu bạn. Hãy cứu chính mình trước.', author: 'Khuyết danh' },
  { text: 'Cánh cửa hạnh phúc không bao giờ đóng hoàn toàn; nếu một cánh đóng, hãy tìm cánh khác đang mở.', author: 'Helen Keller' },
  { text: 'Ngay cả khi bạn đi chậm, bạn vẫn đang đi xa hơn người đứng yên.', author: 'Khuyết danh' },
  { text: 'Kết quả tốt đẹp không bao giờ đến từ vùng an toàn.', author: 'Ben Carson' },
  { text: 'Bạn cần tin vào điều gì đó: trực giác, số phận, cuộc đời, nghiệp lực — bất cứ điều gì. Cách tiếp cận này chưa bao giờ khiến tôi thất vọng.', author: 'Steve Jobs' },
  { text: 'Mỗi ngày bạn tỉnh dậy với một sức mạnh mới và một lý do mới để cảm ơn.', author: 'Khuyết danh' },
  { text: 'Đừng bao giờ nhìn xuống ai ngoại trừ khi bạn đang giơ tay giúp họ đứng dậy.', author: 'Jesse Jackson' },
  { text: 'Cuộc đời giống như đạp xe đạp. Để giữ thăng bằng, bạn phải tiếp tục di chuyển.', author: 'Albert Einstein' },
  { text: 'Dù đêm tối thế nào, bình minh sẽ luôn đến.', author: 'Victor Hugo' },
  { text: 'Hãy là ngọn nến thắp sáng bóng tối, không phải gương phản chiếu nỗi buồn.', author: 'Khuyết danh' },
  { text: 'Thời gian duy nhất bạn không thể tìm lại được chính là thời gian đã qua.', author: 'Khuyết danh' },
  { text: 'Nếu bạn biết mình muốn đi đâu, cả thế giới sẽ nhường đường cho bạn.', author: 'Ralph Waldo Emerson' },
  { text: 'Giới hạn duy nhất trong cuộc đời bạn là những giới hạn bạn tự đặt ra cho mình.', author: 'Les Brown' },
];
