/**
 * Danh sách "Tên Acc" (tên shop) của 6 đội kinh doanh — lưu cứng từ danh bạ
 * Notion "Shop & Kênh" (575 shop, đối chiếu tại thời điểm 2026-08-29) để cột
 * Tên Acc trong Giao Task là select chọn từ danh sách có sẵn thay vì gõ tay
 * tự do. Không đọc trực tiếp từ Notion nên khi danh bạ gốc đổi (thêm/xoá
 * shop, đổi đội) phải cập nhật tay file này. Không dùng 'server-only' vì
 * TaskRowEditor (components/dashboard/task-board.tsx) là client component.
 *
 * `active` = đang chạy ADS hoặc active không ADS (khác Inactive trên Notion).
 * Vài shop bị lặp dòng trên Notion gốc với trạng thái khác nhau (vd đổi từ
 * Inactive sang chạy lại) — trường hợp đó active=true nếu có ít nhất 1 dòng
 * active, tránh việc 1 acc đang chạy thật lại bị giấu đi. Mỗi đội đã loại
 * trùng tên và sắp xếp theo alphabet để ổn định giữa các lần tìm kiếm.
 */
export interface ShopEntry {
  name: string;
  active: boolean;
}

export const SHOPS_BY_TEAM_CODE: Record<string, ShopEntry[]> = {
  KD1: [
    { name: 'Aisha Williford', active: false },
    { name: 'Alex Duran', active: false },
    { name: 'Alex Lucas Foster', active: true },
    { name: 'Amanda Foss', active: false },
    { name: 'Amanda Gulch', active: true },
    { name: 'Amy Atkins', active: true },
    { name: 'Amy Vickery', active: false },
    { name: 'Andrew James Roberts', active: true },
    { name: 'Anthony Brent', active: false },
    { name: 'Anthony Gilbert', active: true },
    { name: 'Barbara Winderlich', active: false },
    { name: 'Barrie Thomas Jones', active: true },
    { name: 'Benjamin Hugh Michael Thomp [tên bị cắt]', active: false },
    { name: 'Benjamin Hugh Michael Thompson', active: true },
    { name: 'Benjamin Ledford', active: false },
    { name: 'Beth White', active: true },
    { name: 'Betty Lambert', active: false },
    { name: 'Bharti Shetye', active: false },
    { name: 'Bill Brentnall', active: false },
    { name: 'Blake Horton', active: true },
    { name: 'Brad Blaylock', active: false },
    { name: 'Brandy L Diggs', active: true },
    { name: 'Brittany Kroll', active: true },
    { name: 'Bryony Rose Carpenter', active: false },
    { name: 'BulkStickerX', active: true },
    { name: 'Carl Crowe', active: true },
    { name: 'Catherine Louise Dawson', active: true },
    { name: 'Chantel Shaw', active: true },
    { name: 'Chargezone5378', active: true },
    { name: 'Chevonda Moses', active: false },
    { name: 'Chris Demarie', active: false },
    { name: 'Chris Matarazzo', active: true },
    { name: 'Christina Kewley', active: true },
    { name: 'Christy Kerley', active: true },
    { name: 'Clinton Wood', active: false },
    { name: 'Clive Terrence Wilson', active: true },
    { name: 'Courtney Duggins', active: true },
    { name: 'Dani Petrie', active: true },
    { name: 'Daniel Clark', active: true },
    { name: 'DANIEL HUANG', active: false },
    { name: 'Danielle Davs', active: false },
    { name: 'Dara Tangeman', active: false },
    { name: 'Dawn Walker', active: false },
    { name: 'Deanna Divino', active: true },
    { name: 'DEVALIRE WADE', active: false },
    { name: 'Deveon Dorsey', active: true },
    { name: 'Diana Pender', active: false },
    { name: 'Dominguez Ross', active: false },
    { name: 'Dominique Jones', active: false },
    { name: 'Donald Graham', active: true },
    { name: 'Donald Perkins', active: false },
    { name: 'Doug Webb', active: false },
    { name: 'Dusan Mihajlovic', active: true },
    { name: 'Dylan George', active: true },
    { name: 'Edward Dutill', active: true },
    { name: 'Elizabeth Gibson', active: false },
    { name: 'Elizabeth Lewis', active: false },
    { name: 'Eric Fields', active: true },
    { name: 'Erica Rouse', active: false },
    { name: 'Eugene Porter', active: true },
    { name: 'Farida Saeed', active: true },
    { name: 'Felice Hardin', active: true },
    { name: 'Freddrina Burse', active: true },
    { name: 'Glenn Conover', active: true },
    { name: 'Glynn Jones', active: true },
    { name: 'Harriet Westenfelder', active: false },
    { name: 'Hazel Mcfadden', active: false },
    { name: 'Heather Henley', active: true },
    { name: 'James Cummings', active: false },
    { name: 'James Hall', active: false },
    { name: 'James Kennedy', active: true },
    { name: 'Jasmine Manley', active: true },
    { name: 'Jasmine Ransom', active: false },
    { name: 'Jason M Ransdell', active: false },
    { name: 'Jeanne McGuiness', active: true },
    { name: 'Jennifer Spalding', active: false },
    { name: 'Jerry Lee Friestad', active: true },
    { name: 'Jessica Kennedy', active: true },
    { name: 'Jessica Morgan', active: false },
    { name: 'Jimmy Lunsford', active: true },
    { name: 'Joanne Ziesmer', active: true },
    { name: 'John Rittenhouse', active: true },
    { name: 'Julie Whalley', active: true },
    { name: 'Juston Boyle', active: false },
    { name: 'Kalani Queensbury', active: false },
    { name: 'Kari Miranowski', active: false },
    { name: 'Karl Lunsford', active: true },
    { name: 'Karsten Amlie', active: false },
    { name: 'Kay Carmean', active: true },
    { name: 'Keith Myers', active: true },
    { name: 'Kelley Argraves', active: true },
    { name: 'Kelly Kriesel', active: true },
    { name: 'Kelly Wallace', active: true },
    { name: 'Kenicia Battle', active: true },
    { name: 'Kerry MacRonald', active: true },
    { name: 'Kevin Kincade', active: false },
    { name: 'Kristi Galofaro', active: true },
    { name: 'Krystal Suddarth', active: true },
    { name: 'Lathena Hill', active: false },
    { name: 'Leah McDermed', active: false },
    { name: 'Less Delisle', active: true },
    { name: 'Lolita M Travis', active: true },
    { name: 'Louie Mark George Lazar', active: true },
    { name: 'Lucy Carpenter', active: false },
    { name: 'Malik Davis', active: true },
    { name: 'Manh Nguyen', active: false },
    { name: 'Marci Glasgow Haire', active: true },
    { name: 'Mark Anthony Colebrook', active: true },
    { name: 'Marquies Mcdonald', active: true },
    { name: 'Martin Butters', active: true },
    { name: 'Mary Booth Amato', active: false },
    { name: 'MEGAN COTTON', active: false },
    { name: 'Michael Anderson', active: false },
    { name: 'Michael Gerard Kneafsey', active: true },
    { name: 'Michael Green', active: true },
    { name: 'Michael Robertson', active: false },
    { name: 'Michael Shaffner', active: false },
    { name: 'Michael Steele', active: false },
    { name: 'Michelle Olguin', active: true },
    { name: 'Mickey Mccoy', active: false },
    { name: 'Mitch Evans', active: true },
    { name: 'Munier Parisi', active: true },
    { name: 'Myron Waddell', active: true },
    { name: 'Nancy L Grover', active: true },
    { name: 'NATALIE SIMMONS', active: false },
    { name: 'Nicholas Alexander Piers Kent', active: false },
    { name: 'PATRICK MURPHY', active: true },
    { name: 'Patrickmurphylove', active: true },
    { name: 'Paul Simon Tansey', active: true },
    { name: 'Peterson Elize', active: false },
    { name: 'Rachel Garner', active: false },
    { name: 'Rafaela Valerio', active: false },
    { name: 'Renee Goldsby', active: false },
    { name: 'Ricardo Otero', active: false },
    { name: 'Rita Seward', active: true },
    { name: 'Robert Michael Cooper', active: true },
    { name: 'Rosanna Sarah Meade', active: true },
    { name: 'Ross Prindle', active: true },
    { name: 'RUBY DIAZ', active: false },
    { name: 'Ryan Mack', active: true },
    { name: 'Sade Smith', active: false },
    { name: 'Sally Shreeves', active: true },
    { name: 'Samein Phin', active: false },
    { name: 'Samuel White', active: true },
    { name: 'Santana Ludaway', active: true },
    { name: 'Sara Louise Morton', active: true },
    { name: 'Sevda Tossoun', active: true },
    { name: 'Shaid Yakub Talati', active: true },
    { name: 'Shanika Richeson', active: true },
    { name: 'Shante Pettway', active: true },
    { name: 'Shea Moyer', active: true },
    { name: 'Shelley Maxwell', active: false },
    { name: 'Sherod Denton', active: true },
    { name: 'Sherwin Mitchell', active: false },
    { name: 'Shirley Tang', active: true },
    { name: 'Shomari Sparkman', active: false },
    { name: 'Silvio A Morales', active: false },
    { name: 'Silviofashiontee', active: true },
    { name: 'Siobhan Stofka', active: false },
    { name: 'Stacy Lam', active: true },
    { name: 'Stephanie Glassman', active: false },
    { name: 'Stephen Alexander Kennedy', active: true },
    { name: 'Stickylogo', active: true },
    { name: 'Suresh Sani', active: false },
    { name: 'Tamara Jackson', active: true },
    { name: 'Teresa Bartlett', active: false },
    { name: 'Terrence Baker', active: true },
    { name: 'Tessia Daivs', active: true },
    { name: 'Torkwase Bullock', active: false },
    { name: 'Travis Emmert', active: true },
    { name: 'Wendell Viccillian', active: false },
    { name: 'Yolanda Barton', active: false },
    { name: 'Yolanda Pankey', active: true },
  ],
  KD2: [
    { name: 'Aaron Macinnis', active: true },
    { name: 'Aaronlee Williams', active: true },
    { name: 'Abel Pesqueira', active: false },
    { name: 'Adam Hewitson', active: true },
    { name: 'Alondus White', active: true },
    { name: 'Altin Bytyqi', active: false },
    { name: 'Amanda Chueches', active: true },
    { name: 'Amber Ramsey', active: true },
    { name: 'Amy Elizabeth Dane Lister', active: false },
    { name: 'Andrea Morrison', active: false },
    { name: 'ANDREA WONG', active: false },
    { name: 'Andrew George Dunning', active: true },
    { name: 'Andrew Marc Hollinson', active: true },
    { name: 'Anne Levendoski', active: true },
    { name: 'Anthony Flack', active: false },
    { name: 'Anthony Muscatello', active: false },
    { name: 'Barbara Stout', active: true },
    { name: 'Bernard Banks', active: false },
    { name: 'Bonnie Ray', active: false },
    { name: 'Brandi Walters', active: false },
    { name: 'Carl Ogeary', active: false },
    { name: 'Carmen Siri', active: false },
    { name: 'Carol Levy', active: false },
    { name: 'Carranza Mayberry', active: false },
    { name: 'Catherine Chatman', active: false },
    { name: 'Catina Gipson', active: false },
    { name: 'Chancy Crenshaw', active: true },
    { name: 'Charles Turpin', active: true },
    { name: 'Charlie Garcia', active: true },
    { name: 'Charlsie A Davis', active: true },
    { name: 'Chaudae Harper', active: false },
    { name: 'Chris Rogers', active: true },
    { name: 'Christopher Dye', active: true },
    { name: 'Cindy Buban', active: true },
    { name: 'Corntney Coleman', active: false },
    { name: 'Cortney Coleman', active: true },
    { name: 'Courtney Moulds', active: true },
    { name: 'Crystal Luttrell', active: true },
    { name: 'Daniel Wolfe', active: true },
    { name: 'Dashawna White', active: false },
    { name: 'David Baker', active: true },
    { name: 'David Poelstra', active: false },
    { name: 'David thornton', active: true },
    { name: 'Dawn Huskey', active: false },
    { name: 'Dawn Moody', active: true },
    { name: 'Dendrick King', active: false },
    { name: 'Denise Adelman', active: true },
    { name: 'Derek Parker', active: true },
    { name: 'Devon Anderson', active: true },
    { name: 'Diane Bryant', active: true },
    { name: 'Don Nelson', active: true },
    { name: 'Dwight Stroad', active: true },
    { name: 'Ebay', active: false },
    { name: 'Elvia Guyton', active: false },
    { name: 'Etsy', active: false },
    { name: 'Faith Gregg', active: false },
    { name: 'Gemma Louise Sandford', active: true },
    { name: 'George Augustine Osei', active: false },
    { name: 'George White', active: false },
    { name: 'Gloria Randall', active: true },
    { name: 'Graham Anthony Jones', active: false },
    { name: 'Guianeya Herrera', active: false },
    { name: 'Gurpreet Kaur Sarai', active: true },
    { name: 'Hannah Hicks', active: true },
    { name: 'Holly Rieger', active: false },
    { name: 'Holly Whitby', active: true },
    { name: 'Imani S Perry', active: false },
    { name: 'Jack Hornsby', active: true },
    { name: 'Jacob Yazdi', active: true },
    { name: 'Jacueline Johnson', active: true },
    { name: 'James Lawrence', active: true },
    { name: 'James Lee', active: false },
    { name: 'Jason Miklian', active: true },
    { name: 'Jawana Peguero', active: true },
    { name: 'Jermaine Edgecomb', active: true },
    { name: 'Jill Yablon', active: false },
    { name: 'Jinu Mathew', active: false },
    { name: 'John Freeman', active: false },
    { name: 'John Maxie', active: false },
    { name: 'Jonah Alva', active: false },
    { name: 'Jonathan Granthan', active: false },
    { name: 'Joseline Stovall', active: false },
    { name: 'Joseph Fefee', active: false },
    { name: 'Joseph Wuest', active: false },
    { name: 'Joshua Bylotas', active: false },
    { name: 'Juris Locs', active: false },
    { name: 'Justin Crosmun', active: true },
    { name: 'Karen Grimsley', active: true },
    { name: 'Kate Cullen', active: true },
    { name: 'Katiya Jenkins', active: false },
    { name: 'Keanah Thomas', active: false },
    { name: 'Kellie Anderson', active: true },
    { name: 'Kenneth Hall', active: true },
    { name: 'Kenyta Beverly', active: false },
    { name: 'Kimberly Parliament', active: false },
    { name: 'Kristimae Knight', active: false },
    { name: 'Kristin Pack', active: false },
    { name: 'Lakeisha Allen', active: true },
    { name: 'Lee Callaghan', active: true },
    { name: 'Linda Harris', active: true },
    { name: 'lucksigns69', active: true },
    { name: 'Lucky', active: true },
    { name: 'Marc Watts', active: false },
    { name: 'Marcus Hanbury Hutchinson', active: true },
    { name: 'Margarito Ochoa', active: false },
    { name: 'Maria Birrueta', active: false },
    { name: 'Maris Rosario', active: true },
    { name: 'Mark Wayne Crimmins', active: true },
    { name: 'Mary Clarke', active: true },
    { name: 'Miesha Jackson', active: true },
    { name: 'Miranda Henson', active: true },
    { name: 'Miranda Mizell', active: false },
    { name: 'Montra Curry', active: false },
    { name: 'Mthandazo Mahlangu', active: true },
    { name: 'Muhammad Jawad Siddiqui', active: true },
    { name: 'Nadia Afsa Khalid', active: false },
    { name: 'Napoleon Hines', active: true },
    { name: 'Nephtali Gonzalez', active: true },
    { name: 'Nicholas Piers Richardson', active: true },
    { name: 'Pamela Heming', active: false },
    { name: 'Prentice Collins', active: true },
    { name: 'Rachel Caroline Thompson', active: true },
    { name: 'Ragan Stukenborg', active: true },
    { name: 'Randall Oshiro', active: true },
    { name: 'Rasaq Balogun', active: false },
    { name: 'Roberta Puckett', active: false },
    { name: 'Romanus Nwaneri', active: false },
    { name: 'Samantha Merle Dsouza', active: true },
    { name: 'Sana Khan', active: true },
    { name: 'Sandra Webb', active: false },
    { name: 'Shannon Lee', active: true },
    { name: 'Sharai Hill', active: false },
    { name: 'Shari Carter', active: false },
    { name: 'Shazid Ahmed', active: true },
    { name: 'Shellene Holloway', active: false },
    { name: 'Shemika Jones', active: true },
    { name: 'Simon Andrew Cockram', active: true },
    { name: 'Solomon Nemetsky', active: true },
    { name: 'Start Carlos', active: false },
    { name: 'Stephanie Lortos', active: false },
    { name: 'Stick', active: true },
    { name: 'Susan Mcclean', active: true },
    { name: 'Taneka Joseph', active: true },
    { name: 'Tiktok US', active: false },
    { name: 'Timia Sims', active: true },
    { name: 'Timothy Evans', active: false },
    { name: 'Twist', active: true },
    { name: 'Veronica Woodruff', active: true },
    { name: 'Victor Lopez', active: true },
    { name: 'Victoria Mintzlaff', active: false },
  ],
  KD3: [
    { name: 'Airica Lawrence', active: false },
    { name: 'Akeevah Jackson', active: false },
    { name: 'Alice Harris Nixon', active: false },
    { name: 'Alka Khindri Rattan', active: false },
    { name: 'Allison Lanning', active: false },
    { name: 'Amanda Bradford', active: true },
    { name: 'Amanda Long', active: false },
    { name: 'Amina Razak', active: false },
    { name: 'Amit Sagu', active: false },
    { name: 'AMY HUDSON - LLC', active: false },
    { name: 'Anastasia Norfleet', active: true },
    { name: 'Angela Estinoza', active: false },
    { name: 'Anne Mcpherson', active: false },
    { name: 'Anthony Brown', active: true },
    { name: 'Anthony Hill', active: false },
    { name: 'Anthony Reed', active: false },
    { name: 'Anurati Patel Long', active: false },
    { name: 'April Mccutcheon', active: true },
    { name: 'Araceli Gomez', active: false },
    { name: 'Ashley Murphy', active: false },
    { name: 'Avangelina Cazares', active: false },
    { name: 'Ben Bacon', active: false },
    { name: 'Bradley W Branch', active: true },
    { name: 'Breanna Clark', active: false },
    { name: 'Brian Carter', active: false },
    { name: 'Brittany Lathan', active: false },
    { name: 'Brittany Watson', active: false },
    { name: 'Brittney Brown', active: false },
    { name: 'Carmelo Rivera', active: false },
    { name: 'Caroline Penfold', active: false },
    { name: 'Chad Poore', active: true },
    { name: 'Charles Bennett', active: false },
    { name: 'Chiquita Rogers', active: false },
    { name: 'Christina Hayes', active: true },
    { name: 'Christine Tee', active: false },
    { name: 'Christopher Moser', active: false },
    { name: 'Christopher Rockwell', active: false },
    { name: 'Claire Crenshaw', active: true },
    { name: 'claudia nelson', active: false },
    { name: 'Connie Yauch', active: true },
    { name: 'Crystal Arellano', active: true },
    { name: 'Crystal Myers', active: false },
    { name: 'Crystal Weber', active: false },
    { name: 'Cynthia Johnson', active: false },
    { name: 'Cynthia Washington', active: false },
    { name: 'Daniel Cadena', active: false },
    { name: 'Daniel Rivera', active: false },
    { name: 'Danielle Hill', active: false },
    { name: 'Danita Kiser', active: false },
    { name: 'Danzel Harrison', active: false },
    { name: 'Dara Tangeman', active: false },
    { name: 'Darryl Shaffer', active: false },
    { name: 'Dean Nelson', active: false },
    { name: 'Deangelo Johnson', active: false },
    { name: 'Denise Mangum', active: false },
    { name: 'Desirae Alston', active: true },
    { name: 'Devin Loureiro', active: false },
    { name: 'Dionne Mahaffey Muhammad', active: true },
    { name: 'Doris Schulz', active: false },
    { name: 'Elizabeth Matos', active: false },
    { name: 'Ellen Fellenz', active: false },
    { name: 'Eric Patterson', active: false },
    { name: 'Erica Oneal', active: false },
    { name: 'Ervin Jackson', active: true },
    { name: 'Etsy Shop Chính', active: true },
    { name: 'Fernando Ruiz', active: true },
    { name: 'Francheska Robinson', active: false },
    { name: 'Francis Laud', active: false },
    { name: 'Frank Sciara', active: false },
    { name: 'Gary Jr Watson', active: false },
    { name: 'George Byrd', active: false },
    { name: 'Georgina Farrell', active: false },
    { name: 'Greg Parker', active: false },
    { name: 'Gregory Price', active: false },
    { name: 'Heather Russell', active: false },
    { name: 'Jaime Verduzco', active: false },
    { name: 'James Lutsko', active: false },
    { name: 'Janice Lowe', active: false },
    { name: 'Jason Gruver', active: false },
    { name: 'Jay Walker', active: true },
    { name: 'Jeanette Andrew', active: true },
    { name: 'Jeewan Kumar Sagu', active: false },
    { name: 'Jeffrey Becker', active: false },
    { name: 'Jennifer Edwards', active: false },
    { name: 'Jeremy Coleman', active: false },
    { name: 'Jessica Howard', active: false },
    { name: 'Jessica Olson', active: true },
    { name: 'Joel Aryeh Gottesman', active: false },
    { name: 'John Bascone', active: true },
    { name: 'John Bourne Shropshire', active: false },
    { name: 'John Mccray', active: false },
    { name: 'John Peter Waldron', active: false },
    { name: 'Johnnie Bryant', active: false },
    { name: 'Johnnie Flemming', active: false },
    { name: 'Jonah Vasquez', active: true },
    { name: 'Joseph A Robertson', active: true },
    { name: 'Justin Brown', active: true },
    { name: 'Justin Powell', active: false },
    { name: 'Kari Mehrwerth', active: false },
    { name: 'Kate Borihane', active: false },
    { name: 'Katherine Dunleavy', active: false },
    { name: 'Katie Jurek', active: false },
    { name: 'Kereem Davis', active: true },
    { name: 'Kevin Hughes', active: false },
    { name: 'Kiesha Stombaugh', active: false },
    { name: 'Kimberly Beaver', active: true },
    { name: 'Kristen Smit', active: false },
    { name: 'Latrese Jackson', active: true },
    { name: 'Laureano Satian', active: false },
    { name: 'Layla Lemmons', active: true },
    { name: 'Lea Tannahill', active: false },
    { name: 'Leslie Moser', active: false },
    { name: 'Linda Estrada', active: false },
    { name: 'Lisa Corey', active: false },
    { name: 'Lois Jordan', active: false },
    { name: 'Maile Thiesen', active: true },
    { name: 'Marcus Johnson', active: false },
    { name: 'Marla Beech', active: false },
    { name: 'Marvin Bailey', active: false },
    { name: 'Matthew Walsh', active: false },
    { name: 'Maylene Salazar', active: true },
    { name: 'Megan Bailey', active: false },
    { name: 'Michael Brown', active: false },
    { name: 'Michael Doyle', active: false },
    { name: 'Michael Howard Evans', active: false },
    { name: 'Michelle Mapps', active: true },
    { name: 'Michelle Spencer', active: false },
    { name: 'Michelle Torres', active: false },
    { name: 'Molly Pena', active: false },
    { name: 'Monica Mitchell', active: false },
    { name: 'Moniquekeya Stallings', active: false },
    { name: 'Nancy Leek', active: false },
    { name: 'Nicole Sanders', active: false },
    { name: 'Olivia Grant', active: true },
    { name: 'Padma Subramanian', active: false },
    { name: 'Patricia Blackwelder', active: false },
    { name: 'Patricia Davis', active: false },
    { name: 'Patricia Lee', active: false },
    { name: 'Porshia Johnson', active: true },
    { name: 'Preston Treadwell', active: false },
    { name: 'Princess Lewis', active: true },
    { name: 'Priscilla Sandifer', active: true },
    { name: 'Rachel Foster', active: false },
    { name: 'Raymond Li', active: false },
    { name: 'Rebecca Leigh Callaghan', active: false },
    { name: 'Richard Brooks', active: true },
    { name: 'Robert Holland', active: false },
    { name: 'Robert Vega', active: false },
    { name: 'Robert Webb', active: false },
    { name: 'Ronald Larkin', active: false },
    { name: 'Rosa Birrueta', active: false },
    { name: 'Rosalia Manuel', active: false },
    { name: 'Russell Sawyer', active: false },
    { name: 'Samantha Cole', active: false },
    { name: 'Samantha Garofalo', active: false },
    { name: 'Sarah Dillon', active: false },
    { name: 'Sarah Timmerman', active: true },
    { name: 'Sates Buddhu', active: true },
    { name: 'Shan Li', active: true },
    { name: 'Shari Min LLC', active: true },
    { name: 'Sherry Enriquez', active: true },
    { name: 'Sirlina Stewart', active: false },
    { name: 'Somphone Bounvassana', active: false },
    { name: 'Staycee Mcdonald', active: false },
    { name: 'Stephanie Sano', active: true },
    { name: 'Stephanie Wright', active: false },
    { name: 'Steven Cooper', active: false },
    { name: 'StickyBeeX', active: true },
    { name: 'Tabitha Gonzalez', active: false },
    { name: 'Tanya Seales', active: true },
    { name: 'Tatiana Green', active: false },
    { name: 'Thelma Woodard', active: true },
    { name: 'Theodore Krumbach', active: false },
    { name: 'Thomas Henley', active: false },
    { name: 'Timothy Gamble', active: true },
    { name: 'TRAMIKA HENSON', active: true },
    { name: 'Tyrone Preston', active: false },
    { name: 'Victoria Carroll', active: true },
    { name: 'Zubair Mohammed', active: false },
  ],
  KD4: [
    { name: 'Alfredo Sanchez', active: false },
    { name: 'Amber Jackson', active: true },
    { name: 'Antonino Coloso Gamboa', active: true },
    { name: 'Ashley Surdi', active: true },
    { name: 'Barbara Marsh', active: false },
    { name: 'Breanna Scott', active: true },
    { name: 'Brittney Carson', active: false },
    { name: 'Casandra Schoenwald', active: true },
    { name: 'Cecil Barber', active: true },
    { name: 'Corina Robles', active: true },
    { name: 'Dalky Velez', active: true },
    { name: 'Dusty Phelps', active: false },
    { name: 'Hastina Fowler', active: false },
    { name: 'Heather Wright', active: false },
    { name: 'Jazmon Ponder', active: false },
    { name: 'Jennifer Alford', active: true },
    { name: 'Jeremy T Miller', active: true },
    { name: 'Jessica Carpenter', active: true },
    { name: 'Jhavana Morgan', active: true },
    { name: 'Keishadia Walker', active: true },
    { name: 'Krystal Gressett', active: true },
    { name: 'Madeline Raymond', active: true },
    { name: 'Marcus Hillmon', active: false },
    { name: 'Maria Lourdes Macias', active: true },
    { name: 'Melissa Shearer', active: false },
    { name: 'Neil Alexander Henry', active: true },
    { name: 'Nimrita Singh', active: true },
    { name: 'Patricia Miller', active: true },
    { name: 'Robert Mercer', active: true },
    { name: 'Robert Paasch', active: true },
    { name: 'Robert Rich', active: true },
    { name: 'Ronald Drayton', active: true },
    { name: 'Ruth Sprouse', active: true },
    { name: 'Samatha Harris', active: true },
    { name: 'Sandy Clark', active: true },
    { name: 'Shakundala Davis', active: true },
    { name: 'Shannon Davis', active: true },
    { name: 'Tanae Womack', active: true },
    { name: 'Taylor Stokes', active: false },
    { name: 'Tiana Paige', active: true },
    { name: 'Toussaint Ewen', active: false },
    { name: 'Vilma Montalvo', active: true },
    { name: 'Yosra Agrebi', active: true },
  ],
  KD5: [
    { name: 'Andrew Neil Ford', active: true },
    { name: 'Christopher Mayney', active: false },
    { name: 'Jennifer Buchanan TTS', active: true },
    { name: 'Jessica Woodrow', active: false },
    { name: 'Julie Price', active: true },
    { name: 'Justin Nations', active: true },
    { name: 'Lauren Pattle', active: false },
    { name: 'Paul John Lamb', active: true },
    { name: 'Richard Clark', active: true },
    { name: 'Richard Elliott', active: true },
    { name: 'Ryan Reid', active: true },
    { name: 'Shareka Phillips TTS', active: false },
    { name: 'Siobhain Mary Phillips', active: true },
    { name: 'Sue E Walker', active: true },
    { name: 'Tenisha Jefferson', active: false },
    { name: 'Widline Ferdinand', active: true },
  ],
  KD6: [
    { name: 'DecoDarlingUS', active: true },
    { name: 'DecoDelightfuls', active: true },
    { name: 'EmbroideryBling', active: true },
    { name: 'FongPatch', active: false },
    { name: 'KindlyPatch', active: true },
    { name: 'OlachezDeco', active: true },
    { name: 'PatchDreamsStudio', active: true },
    { name: 'PatchMyDream', active: true },
    { name: 'PatchNestCO', active: true },
    { name: 'Patchoria', active: true },
    { name: 'PatchPlimaz', active: true },
    { name: 'PurPatches', active: true },
    { name: 'SicupezEmbroidery', active: true },
  ],
};

/** teamCode DB lưu chữ thường (vd 'kd1') — khớp về key hoa 'KD1' ở trên. */
export function shopsForTeamCode(teamCode: string): ShopEntry[] {
  return SHOPS_BY_TEAM_CODE[teamCode.toUpperCase()] ?? [];
}
