/** Import idempotent task thật KD2 các ngày 08, 10, 11 và 12/08/2026. */
import { sql } from '../lib/db';
type Category='Media'|'Support';
type Task={date:string;category:Category;assignee:string;title:string;account?:string;sourceChannel?:string;uploader?:string;videos?:number;product?:string};
const users:Record<string,string>={Lan:'lanpham02',Sơn:'trongson250921',Vân:'thuyvan',Phụng:'phungdo0301',Thu:'hongthu89',Sao:'anhsao1392'};
const d=(day:string)=>`2026-08-${day}`;
const m=(day:string,a:string,title:string,account?:string,sourceChannel?:string,uploader?:string,videos?:number,product:string|null='Playing Card'):Task=>({date:d(day),category:'Media',assignee:users[a],title,account,sourceChannel,uploader,videos,...(product?{product}:{})});
const s=(day:string,a:string,title:string,account?:string,sourceChannel?:string,uploader?:string,videos?:number,product?:string):Task=>({date:d(day),category:'Support',assignee:users[a],title,account,sourceChannel,uploader,videos,product});

const tasks:Task[]=[
  m('08','Lan','The Odyssey Playing card','Jacueline Johnson','Kênh MKT4','Vân',3),
  m('08','Vân','Ghibli Playing card','Barbara Stout','Kênh MKT3','Lan',2),
  m('08','Sơn','Dexter Playing card','Jacueline Johnson','Kênh MKT3','Vân',3),
  m('08','Vân','Jujutsu Kaisen Playing card','Derek Parker','Kênh MKT2','Sao',3),
  m('08','Vân','Sleep Token Playing card','Chris Rogers','Kênh MKT2','Sơn',3),
  m('08','Vân','Sleep Token Playing card','Chris Rogers','Kênh Chính','Sơn',3),
  m('08','Vân','Resident Evil Playing cards','Jason Miklian','MKT4','Thu',3),
  m('08','Vân','Red Dead Redemption Playing card','Jason Miklian','MKT4','Thu',1),
  m('08','Vân','Jujutsu Kaisen Playing card','Derek Parker','Kênh MKT1','Sao',3),
  m('08','Sơn','Dexter Playing card','Jacueline Johnson','Kênh MKT2','Vân',3),
  m('08','Sơn','Dungeon Crawler Playing card','Derek Parker','Kênh MKT4','Sao',3),
  m('08','Sơn','The Odyssey Playing card','Jacueline Johnson','Kênh Chính','Vân',3),
  m('08','Sơn','Sleep Token Playing cards (design 3)','Chris Rogers','Kênh MKT3','Thư',3),
  m('08','Sơn','Sleep Token Playing Cards','Barbara Stout','MKT2','Lan',3),
  m('08','Lan','Studio Ghibli PLC','Barbara Stout','Kênh MKT4','Lan',3),
  m('08','Lan','Sleep Token PLC (mẫu mới)','Barbara Stout','Kênh Chính','Lan',3),
  m('08','Lan','Sleep Token Playing card','Chris Rogers','Kênh MKT4','Thư',3),
  m('08','Lan','Resident Evil Playing card','Jason Miklian','MKT2','Thu',4),
  m('08','Lan','Hollow Knight playing card','Jason Miklian','MKT2','Thu',2),
  s('08','Sao','Check đơn 6shop (không CMS)'),
  s('08','Sao','Check review, rf, tạo FS 5 shop (1)'),
  s('08','Sao','Soạn đơn (UK), add tracking, đổi SKU'),
  s('08','Sao','Gen design Scream plc (1)',undefined,undefined,undefined,undefined,'Playing Card'),
  s('08','Phụng','RDR2 Playing Card','Jason Miklian','Kênh Chính - annepherson','Phụng',2,'Playing Card'),
  s('08','Phụng','RE Playing card','Jason Miklian','Kênh Chính - annepherson','Phụng',3,'Playing Card'),
  s('08','Phụng','RDR2 Playing card','Jason Miklian','Kênh MKT3 - latricialsmith','Phụng',2),
  s('08','Phụng','RE Playing cards','Jason Miklian','Kênh MKT3 - latricialsmith','Phụng',3,'Playing Card'),
  s('08','Phụng','Check shop health, review, refund','Jason Miklian / Nephtali Gonzalez'),
  s('08','Phụng','Add tracking, support KH','lucksigns69'),

  m('10','Lan','Jujutsu Kaisen Playing card','Derek Parker','Kênh MKT1','Sao',3),
  m('10','Lan','Resident Evil Playing cards','Jason Miklian','MKT4','Thu',3),
  m('10','Sơn','Sleep Token Playing card','Chris Rogers','Kênh MKT2','Sơn',2),
  m('10','Sơn','Sleep Token Playing card','Chris Rogers','Kênh Chính','Sơn',2),
  m('10','Sơn','Jujutsu Kaisen Playing card','Derek Parker','Kênh MKT2','Sao',3),
  m('10','Sơn','Sleep Token Playing cards','Chris Rogers','Kênh MKT3','Thư',2),
  m('10','Sơn','Sleep Token Playing Cards','Barbara Stout','MKT2','Lan',3),
  m('10','Sơn','Dexter Playing card','Jacueline Johnson','Kênh MKT3','Vân',3),
  m('10','Sơn','Dungeon Crawler Playing card','Derek Parker','Kênh MKT4','Sao',3),
  m('10','Lan','Hollow Knight playing card','Jason Miklian','MKT2','Thu',1),
  m('10','Lan','Resident Evil Playing card','Jason Miklian','MKT2','Thu',5),
  m('10','Lan','Sleep Token Playing card','Chris Rogers','Kênh MKT4','Thư',3),
  m('10','Lan','Studio Ghibli PLC','Barbara Stout','Kênh MKT4','Lan',2),
  s('10','Phụng','Gen mẫu RE PLC'),
  s('10','Thu','research design Horror VHS Movies P','Jacueline Johnson'),
  s('10','Thu','research mẫu + làm mockup tay + up','Jacueline Johnson'),
  s('10','Thu','Check acc health, SPS & reply Product','Tiktok US'),
  s('10','Thu','thêm variation Glitter cho listing Four','Cindy Buban'),
  s('10','Thu','Soạn đơn clone CMS + gửi 2 đơn clone','Tiktok US'),
  s('10','Phụng','Up 5 listing patch','lucksigns69'),
  s('10','Phụng','Tìm design RDR2'),
  s('10','Sao','Soạn đơn (UK), add tracking, đổi SKU'),
  s('10','Sao','Gen design Scream plc (2)',undefined,undefined,undefined,undefined,'Playing Card'),
  s('10','Sao','Check đơn 6shop (không CMS), print'),
  s('10','Sao','Check review, rf, tạo FS 5 shop (2)'),
  s('10','Phụng','Soạn đơn, add tracking, support KH, import','lucksigns69'),
  s('10','Phụng','Check shop health, review, refund, tạo','Jason Miklian / Nephtali Gonzalez'),
  s('10','Phụng','RDR2 Playing card','Jason Miklian','Kênh MKT3 - latricialsmith','Phụng',2,'Playing Card'),
  s('10','Phụng','RE Playing cards','Jason Miklian','Kênh MKT3 - latricialsmith','Phụng',2,'Playing Card'),
  s('10','Phụng','RE Playing card','Jason Miklian','Kênh Chính - annepherson','Phụng',2,'Playing Card'),
  s('10','Phụng','RDR2 Playing Card','Jason Miklian','Kênh Chính - annepherson','Phụng',2,'Playing Card'),

  m('11','Lan','Hollow Knight playing card (1)','Jason Miklian','MKT2','Thu',2),
  m('11','Vân','Sleep Token Playing card','Chris Rogers','Kênh MKT2','Sơn',3),
  m('11','Vân','Resident Evil Playing cards','Jason Miklian','MKT4','Thu',3),
  m('11','Vân','Sleep Token Playing card','Chris Rogers','Kênh Chính','Sơn',3),
  m('11','Vân','Jujutsu Kaisen Playing card','Derek Parker','Kênh MKT2','Sao',3),
  m('11','Vân','Jujutsu Kaisen Playing card','Derek Parker','Kênh MKT1','Sao',3),
  m('11','Sơn','Sleep Token Playing Cards','Barbara Stout','MKT2','Lan',3),
  m('11','Vân','Ghibli Playing card','Barbara Stout','Kênh MKT3','Lan',2),
  m('11','Sơn','Resident Evil Playing card','James Lawrence','Kênh Chính','Sơn',3),
  m('11','Sơn','Sleep Token Playing cards (design 3)','Chris Rogers','Kênh MKT3','Thư',3),
  m('11','Sơn','AVATAR Playing card','Jacueline Johnson','Kênh MKT3','Vân',3),
  m('11','Sơn','Dungeon Crawler Playing card','Derek Parker','Kênh MKT4','Sao',3),
  m('11','Sơn','AVATAR Playing card','Jacueline Johnson','Kênh MKT2','Vân',3),
  m('11','Lan','Call of duty Card skin','Chancy Crenshaw','MKT1','Thu',2),
  m('11','Lan','Sleep Token Playing card','Chris Rogers','Kênh MKT4','Thư',3),
  m('11','Lan','Resident Evil Playing card','Jason Miklian','MKT2','Thu',4),
  m('11','Lan','Sleep Token PLC','Barbara Stout','Kênh Chính','Lan',3),
  m('11','Lan','Studio Ghibli PLC','Barbara Stout','Kênh MKT4','Lan',3),
  s('11','Thu','1 vid COD Ghost Card Skin','Chancy Crenshaw','Kênh MKT1','Thu',1,'Card Skin'),
  s('11','Thu','-thêm 6 designs mới vào listing kênh','Chancy Crenshaw'),
  s('11','Thu','tối ưu 2 listing Custom Letter Poster','Napoleon Hines'),
  s('11','Thu','research design + làm mockup + up listing','Jacueline Johnson'),
  s('11','Thu','làm lại mockup listing Godfather PLC','Jacueline Johnson'),
  s('11','Thu','làm lại mockup listing Scarface PLC','Jacueline Johnson'),
  s('11','Thu','Sửa nội dung Shipping Time trong description','James Lawrence'),
  s('11','Thu','Check made-to-order & acc health các','Tiktok US'),
  s('11','Phụng','Gen mẫu Nier PLC'),
  s('11','Thu','• Soạn đơn clone CMS • Tạo Flash sale','Tiktok US'),
  s('11','Phụng','Đổi MTO 22 listing PLC','Jason Miklian'),
  s('11','Phụng','Soạn đơn, add tracking, support KH, import','lucksigns69'),
  s('11','Phụng','Check shop health, review, refund','Jason Miklian / Nephtali Gonzalez'),
  s('11','Phụng','RE Playing cards','Jason Miklian','Kênh MKT3 - latricialsmith','Phụng',3,'Playing Card'),
  s('11','Phụng','RE Playing card','Jason Miklian','Kênh Chính - annepherson','Phụng',3,'Playing Card'),
  s('11','Phụng','RDR2 Playing cards','Jason Miklian','Kênh MKT3 - latricialsmith','Phụng',2),

  m('12','Vân','Horror HLW Playing card','Jacueline Johnson','Kênh MKT4','Vân',2),
  m('12','Sơn','Resident Evil Playing card (bộ mới)','Chancy Crenshaw','Kênh MKT2','Sơn',2),
  m('12','Lan','nier: automata PLC','Justin Crosmun','Kênh MKT1','Lan',3),
  m('12','Vân','Jujutsu Kaisen Playing card','Derek Parker','Kênh MKT2','Sao',3),
  m('12','Vân','Jujutsu Kaisen Playing card','Derek Parker','Kênh MKT1','Sao',3),
  m('12','Vân','Resident Evil Playing cards (mẫu mới)','Jason Miklian','MKT4','Thu',3),
  m('12','Vân','Sleep Token Playing card','Chris Rogers','Kênh Chính','Sơn',3),
  m('12','Sơn','Horror HLW Playing card','Jacueline Johnson','Kênh MKT4','Vân',3),
  m('12','Sơn','Horror HLW Playing card','Jacueline Johnson','Kênh Chính','Vân',3),
  m('12','Vân','Sleep Token Playing card','Chris Rogers','Kênh MKT2','Sơn',3),
  m('12','Sơn','Dungeon Crawler Card Skin','Derek Parker','Kênh MKT3','Sao',3),
  m('12','Sơn','Dungeon Crawler Playing card','Derek Parker','Kênh MKT4','Sao',3),
  m('12','Sơn','Sleep Token Playing cards','Chris Rogers','Kênh MKT3','Thư',3),
  m('12','Lan','nier: automata PLC','Justin Crosmun','Kênh Chính','Lan',3),
  m('12','Lan','Sleep Token Playing card','Chris Rogers','Kênh MKT4','Thư',3),
  m('12','Lan','Resident Evil Playing card','Jason Miklian','MKT2','Thu',4),
  m('12','Lan','Red Dead playing card','Jason Miklian','MKT2','Thu',2),
  m('12','Lan','Call of duty Card skin','Chancy Crenshaw','MKT1','Sơn',2),
  s('12','Sao','Gen ảnh mockup, up 1 lst kênh RE plc'),
  s('12','Sao','Gen ảnh mockup, up 1 lst kênh HLW Horror'),
  s('12','Sao','Check refund, review, tạo FS 5shop'),
  s('12','Sao','Soạn đơn (UK), add tracking, sp KH'),
  s('12','Thu','up listing kênh Ghost in Bathtub Card','Shemika Jones'),
  s('12','Thu','sửa lại giá up spam cho 38 listings Wrapping','Timia Sims'),
  s('12','Thu','sửa variation size + giá + decription của','Napoleon Hines'),
  s('12','Phụng','Up listing N:A Playing cards','Justin Crosmun'),
  s('12','Phụng','RDR2 Playing cards','Jason Miklian','Kênh Chính - annepherson','Phụng',2,'Playing Card'),
  s('12','Thu','làm lại ảnh main listing spam Sleep Token','Jason Miklian'),
  s('12','Thu','sửa giá các listing up spam Calendar 2027','Jacueline Johnson'),
  s('12','Thu','up spam Micheal Jackson Calendar 2027','Chancy Crenshaw'),
  s('12','Thu','support tin nhắn 2 KH','Chris Rogers'),
  s('12','Thu','reply 20 product ratings và support 1','David Baker'),
  s('12','Thu','Check made-to-order & acc health các','Tiktok US'),
  s('12','Thu','• Soạn đơn clone CMS • Tạo Flash sale','Tiktok US'),
  s('12','Thu','• Check trạng thái đơn sắp shiplate: support','Tiktok US'),
  s('12','Phụng','Gen mẫu Nier PLC'),
  s('12','Phụng','RDR2 Playing cards','Jason Miklian','Kênh MKT3 - latricialsmith','Phụng',2,'Playing Card'),
  s('12','Phụng','RE Playing card','Jason Miklian','Kênh Chính - annepherson','Phụng',3,'Playing Card'),
  s('12','Phụng','RE Playing cards','Jason Miklian','Kênh MKT3 - latricialsmith','Phụng',3,'Playing Card'),
  s('12','Phụng','Check shop health, review, refund','Jason Miklian / Nephtali Gonzalez'),
  s('12','Phụng','Soạn đơn, add tracking, support KH, import','lucksigns69'),
];

async function main(){
  const team=await sql.query(`SELECT id FROM teams WHERE code='kd2'`); if(!team[0])throw new Error('Không tìm thấy KD2.'); const teamId=team[0].id as number;
  const cats=await sql.query(`SELECT id,name FROM team_task_categories WHERE team_id=$1 AND name=ANY($2::text[])`,[teamId,['Media','Support']]); const categoryIds=new Map(cats.map(r=>[String(r.name),r.id as number]));
  if(!categoryIds.has('Media')||!categoryIds.has('Support'))throw new Error('KD2 thiếu nhóm Media hoặc Support.');
  const usernames=[...new Set(tasks.map(t=>t.assignee))]; const members=await sql.query(`SELECT u.id,u.username FROM team_members tm JOIN users u ON u.id=tm.user_id WHERE tm.team_id=$1 AND u.username=ANY($2::text[])`,[teamId,usernames]); const memberIds=new Map(members.map(r=>[String(r.username),r.id as number]));
  const missing=usernames.filter(u=>!memberIds.has(u)); if(missing.length)throw new Error(`Thiếu thành viên: ${missing.join(', ')}`);
  const manager=await sql.query(`SELECT user_id FROM team_members WHERE team_id=$1 AND role='manager' ORDER BY user_id LIMIT 1`,[teamId]); const createdBy=(manager[0]?.user_id as number|undefined)??null;
  let created=0,skipped=0;
  for(const t of tasks){const values=[teamId,categoryIds.get(t.category),t.date,memberIds.get(t.assignee),t.account??null,t.title,t.uploader??null,t.videos??null,t.product??null,t.sourceChannel?`Kênh: ${t.sourceChannel}`:null,createdBy]; const rows=await sql.query(`INSERT INTO tasks(team_id,category_id,task_date,assignee_user_id,account_name,title,channel,video_count,product,note,status,created_by) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'done',$11 WHERE NOT EXISTS(SELECT 1 FROM tasks WHERE team_id=$1 AND category_id=$2 AND task_date=$3 AND assignee_user_id=$4 AND account_name IS NOT DISTINCT FROM $5::text AND title=$6 AND channel IS NOT DISTINCT FROM $7::text AND video_count IS NOT DISTINCT FROM $8::integer AND product IS NOT DISTINCT FROM $9::text AND note IS NOT DISTINCT FROM $10::text) RETURNING id`,values); if(rows.length)created++;else skipped++;}
  console.log(`KD2 08-12/08/2026: tạo ${created}, bỏ qua ${skipped} task đã tồn tại.`);
}
main().catch(e=>{console.error(e);process.exit(1)});
