/** Import idempotent task thật KD2 các ngày 17–20/08/2026. */
import { sql } from '../lib/db';
type Category='Media'|'Support';type Task={date:string;category:Category;assignee:string;title:string;account?:string;sourceChannel?:string;uploader?:string;videos?:number;product?:string};
const users:Record<string,string>={Lan:'lanpham02',Sơn:'trongson250921',Vân:'thuyvan',Phụng:'phungdo0301',Thu:'hongthu89',Sao:'anhsao1392'};const d=(x:string)=>`2026-08-${x}`;
const m=(day:string,a:string,title:string,account?:string,sourceChannel?:string,uploader?:string,videos?:number,product:string|null='Playing Card'):Task=>({date:d(day),category:'Media',assignee:users[a],title,account,sourceChannel,uploader,videos,...(product?{product}:{})});
const s=(day:string,a:string,title:string,account?:string,sourceChannel?:string,uploader?:string,videos?:number,product?:string):Task=>({date:d(day),category:'Support',assignee:users[a],title,account,sourceChannel,uploader,videos,product});
const tasks:Task[]=[
  m('17','Sơn','Resident Evil Playing cards (mẫu màu)','Jason Miklian','MKT4','Thu',3),
  m('17','Vân','Resident Evil Playing cards (mẫu màu)','Jason Miklian','Kênh Chính','Thu',3),
  m('17','Vân','Jujutsu Kaisen Playing card','Derek Parker','Kênh MKT1','Sao',3),
  m('17','Vân','Sleep Token Playing card','Chris Rogers','Kênh Chính','Sơn',3),
  m('17','Vân','Sleep Token Playing card','Chris Rogers','Kênh MKT2','Sơn',3),
  m('17','Vân','Scream Playing card','Chris Rogers','Kênh MKT1','Sơn',3),
  m('17','Vân','Horror HLW Playing card','Jacueline Johnson','Kênh Chính','Vân',2),
  m('17','Sơn','nier: automata PLC','Justin Crosmun','Kênh Chính','Lan',3),
  m('17','Sơn','Horror HLW Playing card','Jacueline Johnson','Kênh MKT4','Vân',2),
  m('17','Sơn','Horror HLW Playing card','Jacueline Johnson','Kênh MKT2','Vân',3),
  m('17','Sơn','Ghost face Playing cards','Chris Rogers','Kênh MKT3','Thư',3),
  m('17','Sơn','Dungeon Crawler card skin','Derek Parker','Kênh MKT4','Sao',3,'Card Skin'),
  s('17','Thu','• Soạn đơn clone CMS + gửi clone','Tiktok US'),
  s('17','Thu','up listing kênh DCC Wrpp','Derek Parker'),
  s('17','Thu','san 10 designs vào listing kênh DCC','Derek Parker'),
  s('17','Thu','up listing kênh Witchy Gothic Wrpp','Aaron Macinnis'),
  s('17','Thu','Làm mockup ảnh main 8 mẫu PLC','Tiktok US'),
  s('17','Sao','Check rf, review 5shop (1)'),
  s('17','Sao','Up 50 Halloween Rug','Aaronlee Williams / Alona','Mỗi shop 50 listing',undefined,undefined,'Wrapping Paper'),
  s('17','Sao','Soạn đơn (UK), add tracking, đổi SKU'),
  s('17','Sao','Task trống'),

  m('18','Vân','Scream Playing card','Chris Rogers','Kênh MKT1','Sơn',3),
  m('18','Vân','Sleep Token Playing card','Chris Rogers','Kênh MKT2','Sơn',3),
  m('18','Vân','Scream HLW Playing card','Jacueline Johnson','Kênh Chính','Vân',2),
  m('18','Vân','Dungeon Crawler Coin','Derek Parker','Kênh MKT1','Lan',3,'Coin'),
  m('18','Vân','Sleep Token Playing card','Chris Rogers','Kênh Chính','Sơn',3),
  m('18','Vân','Resident Evil Playing cards (mẫu màu)','Jason Miklian','Kênh Chính','Thu',3),
  m('18','Sơn','Dungeon Crawler Coin','Derek Parker','Kênh MKT4','Sao',3,'Coin'),
  m('18','Sơn','Ghost face Playing cards','Chris Rogers','Kênh MKT3','Thư',3),
  m('18','Sơn','Horror HLW Playing card','Jacueline Johnson','Kênh MKT2','Vân',3),
  m('18','Sơn','Horror HLW Playing card','Jacueline Johnson','Kênh MKT4','Vân',2),
  m('18','Sơn','Resident Evil Playing cards (mẫu màu)','Jason Miklian','MKT4','Thu',3),
  m('18','Sơn','Halloween Wrapping paper','Aaron Macinnis','Kênh Chính','Thu',3,'Wrapping Paper'),
  s('18','Thu','1 vid Custom Letter Poster','Napoleon Hines',undefined,undefined,1,'Poster'),
  s('18','Phụng','Tìm design Project Hail Mary PLC'),
  s('18','Phụng','Gen mockup, up Hamilton PLC','Jason Miklian / Barbara Stout'),
  s('18','Phụng','Check shop health, trả lời review, refund','Jason Miklian / James Lawrence'),
  s('18','Phụng','Tìm design Animal smoking PLC'),
  s('18','Phụng','Soạn đơn, add tracking UK, note ads'),
  s('18','Phụng','Soạn đơn, add tracking, support KH, import','lucksigns69'),
  s('18','Thu','• Soạn đơn clone CMS • Tạo Flash sale','Tiktok US'),
  s('18','Thu','tối ưu 2 listing Custom poster đang ra','Napoleon Hines'),
  s('18','Thu','up spam 5 listings Custom Name & Room','Napoleon Hines'),
  s('18','Thu','up 8 listings spam Custom Name & Room','Napoleon Hines'),
  s('18','Thu','soạn decription cho sản phẩm mới + up','Amber Ramsey'),
  s('18','Sao','Up 50 Halloween Rug (1)','Aaronlee Williams / Alona','Mỗi shop 50 listing',undefined,undefined,'Wrapping Paper'),

  m('19','Lan','Dungeon crawler card Wrapping paper','Derek Parker','MKT3','Sao',2,'Wrapping Paper'),
  m('19','Lan','Creepy paper Wrapping paper (christmas)','Ragan Stukenborg','Kênh chính','Lan',3,'Wrapping Paper'),
  m('19','Lan','Dungeon crawler card Wrapping paper','Derek Parker','MKT2','Sao',3,'Wrapping Paper'),
  m('19','Lan','Creepy Doll Wrapping paper','Aaron Macinnis','MKT1','Thu',3,'Wrapping Paper'),
  m('19','Lan','Hollow Knight Playing cards','Jason Miklian','MKT3 - latricialsmith','Phụng',3),
  m('19','Sơn','Resident Evil Playing cards (mẫu màu)','Jason Miklian','MKT4','Thư',3),
  m('19','Vân','Sleep Token Playing card','Chris Rogers','Kênh Chính','Sơn',3),
  m('19','Vân','Resident Evil Playing cards (mẫu màu)','Jason Miklian','Kênh Chính','Phụng',3),
  m('19','Vân','Scream HLW Playing card','Jacueline Johnson','Kênh Chính','Vân',2),
  m('19','Vân','Dungeon Crawler Coin','Derek Parker','Kênh MKT1','Sao',3,'Coin'),
  m('19','Vân','Scream Playing card','Chris Rogers','Kênh MKT2','Sơn',3),
  m('19','Vân','Scream Playing card','Chris Rogers','Kênh MKT1','Sơn',3),
  m('19','Lan','Creepy Doll Wrapping paper','Aaron Macinnis','Kênh Chính','Thu',3,'Wrapping Paper'),
  m('19','Sơn','Red Dead Playing cards','Jason Miklian','Kênh MKT2','Thư',3),
  m('19','Sơn','Horror HLW Playing card','Jacueline Johnson','Kênh MKT4','Vân',2),
  m('19','Sơn','Horror HLW Playing card','Jacueline Johnson','Kênh MKT2','Vân',3),
  m('19','Sơn','Dungeon Crawler Coin','Derek Parker','Kênh MKT4','Sao',3,'Coin'),
  m('19','Sơn','Ghost face Playing cards','Chris Rogers','Kênh MKT3','Thư',3),
  s('19','Thu','up spam 1 listing Set Custom','Napoleon Hines'),
  s('19','Phụng','Tìm design Animal smoking PLC'),
  s('19','Phụng','Tìm design, gen mẫu Twilight PLC'),
  s('19','Thu','1 vid Custom Letter Poster','Napoleon Hines',undefined,'Giang',1,'Poster'),
  s('19','Thu','up 2 listings spam HLW Round Rug','Amber Ramsey'),
  s('19','Thu','Gen 5 mẫu Horror Movies Round Rug','Gloria Randall'),
  s('19','Thu','làm mockup + thêm bộ bài design mới','Chris Rogers'),
  s('19','Thu','tối ưu listing + thêm variation Glitter','Cindy Buban'),
  s('19','Thu','• Soạn đơn clone CMS • Tạo Flash sale','Tiktok US'),
  s('19','Sao','Up 50 Halloween Card Skin (nhớ giảm giá)','Don Nelson / Cindy Buban','up mỗi shop 25 listing',undefined,undefined,'Card Skin'),
  s('19','Phụng','Gen mockup, up Scarface PLC','Jason Miklian'),
  s('19','Phụng','Check shop health, trả lời review, refund','Jason Miklian / James Lawrence'),
  s('19','Phụng','Soạn đơn, add tracking, support KH, import','lucksigns69'),

  m('20','Vân','Scream Playing card','Chris Rogers','Kênh MKT2','Sơn',3),
  m('20','Vân','Dungeon Crawler Coin','Derek Parker','Kênh MKT1','Sao',3,'Coin'),
  m('20','Vân','Sleep Token Playing card','Chris Rogers','Kênh Chính','Sơn',3),
  m('20','Vân','Scream Playing card','Chris Rogers','Kênh MKT1','Sơn',3),
  m('20','Vân','Scream HLW Playing card','Jacueline Johnson','Kênh Chính','Vân',2),
  m('20','Vân','Resident Evil Playing cards (mẫu màu)','Jason Miklian','Kênh Chính','Phụng',3),
  m('20','Sơn','Ghost face Playing cards','Chris Rogers','Kênh MKT3','Thư',3),
  m('20','Sơn','Dungeon Crawler Coin','Derek Parker','Kênh MKT4','Sao',3,'Coin'),
  m('20','Sơn','Scream HLW Playing card','Jacueline Johnson','Kênh MKT2','Vân',3),
  m('20','Sơn','Scream HLW Playing card','Jacueline Johnson','Kênh MKT4','Vân',2),
  m('20','Sơn','Resident Evil Playing cards (mẫu màu)','Jason Miklian','MKT4','Thư',3),
  m('20','Sơn','Hollow Knight Playing cards','Jason Miklian','Kênh MKT2','Thư',3),
  m('20','Lan','Hollow Knight Playing cards (1)','Jason Miklian','MKT3 - latricialsmith','Phụng',3),
  m('20','Lan','Creepy paper Wrapping paper (christmas)','Ragan Stukenborg','Kênh chính','Lan',3,'Wrapping Paper'),
  m('20','Lan','Dungeon crawler card Wrapping paper','Derek Parker','MKT3','Sao',2,'Wrapping Paper'),
  m('20','Lan','Dungeon crawler coin','Derek Parker','MKT2','Sao',3,'Wrapping Paper'),
  m('20','Lan','Creepy Doll Wrapping paper','Aaron Macinnis','MKT1','Thu',3,'Wrapping Paper'),
  m('20','Lan','Creepy Doll Wrapping paper','Aaron Macinnis','Kênh Chính','Thu',3,'Wrapping Paper'),
  s('20','Thu','Check made-to-order & account health','Tiktok US'),
  s('20','Thu','up 1 listing Scream PLC','Ebay'),
  s('20','Phụng','Gen mockup, sửa listing kênh Ghostface','Chris Rogers'),
  s('20','Thu','• Soạn đơn clone CMS • Tạo Flash sale','Tiktok US'),
  s('20','Thu','thêm 2 mẫu Scream PLC vào listing kênh','Jacueline Johnson'),
  s('20','Thu','gen mẫu COD Ghost PLC','Chancy Crenshaw'),
  s('20','Thu','gen mẫu Fourth Wing PLC','Shemika Jones'),
  s('20','Thu','Gen 10 mẫu Horror Characters Round Rug','Tiktok US'),
  s('20','Thu','1 vid COD Ghosts card skin','Chancy Crenshaw',undefined,'Thu',1,'Card Skin'),
  s('20','Thu','1 vid Fourth Wing card skin','Shemika Jones',undefined,'Thu',1,'Card Skin'),
  s('20','Phụng','Gen 2 mẫu Twilight PLC'),
  s('20','Sao','Up 50 Halloween Card Skin (nhớ giảm giá)','Don Nelson / Cindy Buban','up mỗi shop 25 listing',undefined,undefined,'Card Skin'),
  s('20','Phụng','Gen 15 mẫu Animal smoking PLC'),
  s('20','Phụng','Add tracking, support KH','lucksigns69'),
  s('20','Phụng','Check shop health, trả lời review, refund','Jason Miklian / James Lawrence'),
];
async function main(){const team=await sql.query(`SELECT id FROM teams WHERE code='kd2'`);if(!team[0])throw new Error('Không tìm thấy KD2.');const teamId=team[0].id as number;const cats=await sql.query(`SELECT id,name FROM team_task_categories WHERE team_id=$1 AND name=ANY($2::text[])`,[teamId,['Media','Support']]);const categoryIds=new Map(cats.map(r=>[String(r.name),r.id as number]));if(!categoryIds.has('Media')||!categoryIds.has('Support'))throw new Error('KD2 thiếu nhóm Media hoặc Support.');const usernames=[...new Set(tasks.map(t=>t.assignee))];const members=await sql.query(`SELECT u.id,u.username FROM team_members tm JOIN users u ON u.id=tm.user_id WHERE tm.team_id=$1 AND u.username=ANY($2::text[])`,[teamId,usernames]);const memberIds=new Map(members.map(r=>[String(r.username),r.id as number]));const missing=usernames.filter(u=>!memberIds.has(u));if(missing.length)throw new Error(`Thiếu thành viên: ${missing.join(', ')}`);const manager=await sql.query(`SELECT user_id FROM team_members WHERE team_id=$1 AND role='manager' ORDER BY user_id LIMIT 1`,[teamId]);const createdBy=(manager[0]?.user_id as number|undefined)??null;let created=0,skipped=0;for(const t of tasks){const values=[teamId,categoryIds.get(t.category),t.date,memberIds.get(t.assignee),t.account??null,t.title,t.uploader??null,t.videos??null,t.product??null,t.sourceChannel?`Kênh: ${t.sourceChannel}`:null,createdBy];const rows=await sql.query(`INSERT INTO tasks(team_id,category_id,task_date,assignee_user_id,account_name,title,channel,video_count,product,note,status,created_by) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'done',$11 WHERE NOT EXISTS(SELECT 1 FROM tasks WHERE team_id=$1 AND category_id=$2 AND task_date=$3 AND assignee_user_id=$4 AND account_name IS NOT DISTINCT FROM $5::text AND title=$6 AND channel IS NOT DISTINCT FROM $7::text AND video_count IS NOT DISTINCT FROM $8::integer AND product IS NOT DISTINCT FROM $9::text AND note IS NOT DISTINCT FROM $10::text) RETURNING id`,values);if(rows.length)created++;else skipped++;}console.log(`KD2 17-20/08/2026: tạo ${created}, bỏ qua ${skipped} task đã tồn tại.`);}main().catch(e=>{console.error(e);process.exit(1)});
