/** Import idempotent task thật KD2 các ngày 13–15/08/2026. */
import { sql } from '../lib/db';
type Category='Media'|'Support';
type Task={date:string;category:Category;assignee:string;title:string;account?:string;sourceChannel?:string;uploader?:string;videos?:number;product?:string};
const users:Record<string,string>={Lan:'lanpham02',Sơn:'trongson250921',Vân:'thuyvan',Phụng:'phungdo0301',Thu:'hongthu89',Sao:'anhsao1392'};
const d=(day:string)=>`2026-08-${day}`;
const m=(day:string,a:string,title:string,account?:string,sourceChannel?:string,uploader?:string,videos?:number,product:string|null='Playing Card'):Task=>({date:d(day),category:'Media',assignee:users[a],title,account,sourceChannel,uploader,videos,...(product?{product}:{})});
const s=(day:string,a:string,title:string,account?:string,sourceChannel?:string,uploader?:string,videos?:number,product?:string):Task=>({date:d(day),category:'Support',assignee:users[a],title,account,sourceChannel,uploader,videos,product});
const tasks:Task[]=[
  m('13','Vân','Ghostface Playing card','Chris Rogers','Kênh MKT2','Sơn',3),
  m('13','Vân','Jujutsu Kaisen Playing card','Derek Parker','Kênh MKT1','Sao',3),
  m('13','Vân','Resident Evil Playing cards (mẫu mới)','Jason Miklian','MKT4','Thu',3),
  m('13','Vân','Jujutsu Kaisen Playing card','Derek Parker','Kênh MKT2','Sao',3),
  m('13','Vân','Sleep Token Playing card','Chris Rogers','Kênh Chính','Sơn',3),
  m('13','Vân','Horror HLW Playing card','Jacueline Johnson','Kênh MKT4','Vân',2),
  m('13','Sơn','Dungeon Crawler card skin','Derek Parker','Kênh MKT4','Sao',3),
  m('13','Sơn','Ghost face Playing cards','Chris Rogers','Kênh MKT3','Thư',3),
  m('13','Sơn','Jujutsu Kaisen Playing Card','Derek Parker','Kênh MKT3','Sao',3),
  m('13','Sơn','Horror HLW Playing card','Jacueline Johnson','Kênh MKT4','Vân',3),
  m('13','Sơn','Horror HLW Playing card','Jacueline Johnson','Kênh Chính','Vân',3),
  m('13','Sơn','Resident Evil Playing card (bộ mới)','Chancy Crenshaw','Kênh MKT2','Sơn',2),
  m('13','Lan','Resident Evil Playing card (bộ mới)','Chancy Crenshaw','MKT1','Sơn',2),
  m('13','Lan','Resident Evil Playing card','Jason Miklian','MKT2','Thu',4),
  m('13','Lan','Red Dead playing card','Jason Miklian','MKT2','Thu',2),
  m('13','Lan','Sleep Token Playing card','Chris Rogers','Kênh MKT4','Thư',3),
  m('13','Lan','nier: automata PLC','Justin Crosmun','Kênh MKT1','Lan',3),
  m('13','Lan','nier: automata PLC','Justin Crosmun','Kênh Chính','Lan',3),
  s('13','Sao','Up spam 15 lst HLW movie pjs','Karen Grimsley',undefined,undefined,undefined,'Pajamas'),
  s('13','Sao','Check rf, review 5shop'),
  s('13','Sao','Soạn đơn (US,UK), đổi SKU, add tracking'),
  s('13','Sao','Up spam 20 lst wpaper (HLW)','Aaron Macinnis',undefined,undefined,undefined,'Wrapping Paper'),
  s('13','Phụng','Soạn đơn, add tracking, support KH, import','lucksigns69'),
  s('13','Phụng','Check shop health, review, refund','Jason Miklian / Nephtali Gonzalez'),
  s('13','Phụng','RDR2 Playing cards','Jason Miklian','Kênh Chính - annepherson','Phụng',1,'Playing Card'),
  s('13','Phụng','RE Playing card','Jason Miklian','Kênh Chính - annepherson','Phụng',3,'Playing Card'),
  s('13','Phụng','Hollow Knight Playing cards','Jason Miklian','Kênh MKT3 - latricialsmith','Phụng',2,'Playing Card'),
  s('13','Phụng','RE Playing cards','Jason Miklian','Kênh MKT3 - latricialsmith','Phụng',3,'Playing Card'),
  s('13','Phụng','Gen mockup, sửa listing kênh RE Plc','Jason Miklian'),

  m('14','Vân','Jujutsu Kaisen Playing card','Derek Parker','Kênh MKT2','Sao',3),
  m('14','Vân','Sleep Token Playing card','Chris Rogers','Kênh Chính','Sơn',3),
  m('14','Vân','Resident Evil Playing cards (mẫu màu)','Jason Miklian','MKT4','Thu',3),
  m('14','Vân','Horror HLW Playing card','Jacueline Johnson','Kênh MKT3','Vân',2),
  m('14','Vân','Jujutsu Kaisen Playing card','Derek Parker','Kênh MKT1','Sao',3),
  m('14','Vân','Ghostface Playing card','Chris Rogers','Kênh MKT2','Sơn',3),
  m('14','Sơn','Horror HLW Playing card','Jacueline Johnson','Kênh Chính','Vân',3),
  m('14','Sơn','Horror HLW Playing card','Jacueline Johnson','Kênh MKT4','Vân',3),
  m('14','Sơn','Ghost face Playing cards','Chris Rogers','Kênh MKT3','Thư',3),
  m('14','Sơn','Dungeon Crawler card skin','Derek Parker','Kênh MKT4','Sao',3),
  m('14','Sơn','Jujutsu Kaisen Playing Card','Derek Parker','Kênh MKT3','Sao',3),
  m('14','Sơn','Resident Evil Playing card (mẫu màu cũ)','Chancy Crenshaw','Kênh MKT2','Sơn',3),
  m('14','Lan','nier: automata PLC','Justin Crosmun','Kênh Chính','Lan',3),
  m('14','Lan','nier: automata PLC','Justin Crosmun','Kênh MKT1','Lan',3),
  m('14','Lan','Scream Ghostface Playing card','Chris Rogers','Kênh MKT4','Thư',3),
  m('14','Lan','Resident Evil Playing card','Jason Miklian','MKT2','Thu',4),
  m('14','Lan','Red Dead playing card','Jason Miklian','MKT2','Thu',2),
  m('14','Lan','nier: automata PLC','Justin Crosmun','Kênh MKT2','Lan',2),
  s('14','Thu','Sửa lại variation listing Adult Humor Wrapping','Don Nelson'),
  s('14','Thu','up listing spam Malcolm X Calendar 2027','Chancy Crenshaw'),
  s('14','Thu','1 vid AI COD Ghost Card Skin','Chancy Crenshaw','Kênh MKT1',undefined,1,'Card Skin'),
  s('14','Thu','Sửa giá các listing up spam Card Skin','Cindy Buban'),
  s('14','Thu','gen mẫu + làm mockup + up listing','Chancy Crenshaw'),
  s('14','Thu','tạo warehouse + promotion + flash sale','Susan Mcclean'),
  s('14','Thu','Check trạng thái + nhắn sup push đơn','Napoleon Hines'),
  s('14','Thu','Sửa lại kích thước cho 17 listings spam','Shari Carter'),
  s('14','Thu','Task trống','Tiktok US'),
  s('14','Thu','• Soạn đơn clone CMS • Tạo Flash sale','Tiktok US'),
  s('14','Phụng','Gen mockup, add design vào listing kênh','Justin Crosmun'),
  s('14','Sao','Up spam 20 lst wpaper (Gothic HLW)','Aaron Macinnis',undefined,undefined,undefined,'Wrapping Paper'),
  s('14','Sao','Check rf, review 5shop'),
  s('14','Sao','Soạn đơn (UK), add tracking, đổi SKU'),
  s('14','Sao','Up spam 20 lst wpaper (Gothic HLW)','lucksigns69'),
  s('14','Phụng','Hollow Knight Playing cards, chụp mockup','Jason Miklian','Kênh MKT3 - latricialsmith','Phụng',2,'Playing Card'),
  s('14','Phụng','RE Playing cards','Jason Miklian','Kênh MKT3 - latricialsmith','Phụng',3,'Playing Card'),
  s('14','Phụng','Gen mockup, add design vào listing Hollow Knight','Jason Miklian'),
  s('14','Phụng','RDR2 Playing cards','Jason Miklian','Kênh Chính - annepherson','Phụng',2,'Playing Card'),
  s('14','Phụng','RE Playing card','Jason Miklian','Kênh Chính - annepherson','Phụng',3,'Playing Card'),
  s('14','Phụng','Soạn đơn, add tracking, support KH, import','lucksigns69'),
  s('14','Phụng','Check shop health, review, refund','Jason Miklian / Nephtali Gonzalez'),

  m('15','Vân','Sleep Token Playing card','Chris Rogers','Kênh MKT2','Sơn',3),
  m('15','Sơn','Resident Evil Playing cards (mẫu màu)','Jason Miklian','MKT4','Thu',3),
  m('15','Vân','Horror HLW Playing card','Jacueline Johnson','Kênh MKT3','Vân',2),
  m('15','Vân','Sleep Token Playing card','Chris Rogers','Kênh MKT1','Sơn',3),
  m('15','Vân','Sleep Token Playing card','Chris Rogers','Kênh Chính','Sơn',3),
  m('15','Vân','Jujutsu Kaisen Playing card','Derek Parker','Kênh MKT1','Sao',3),
  m('15','Sơn','Resident Evil Playing card (mẫu màu cũ)','Chancy Crenshaw','Kênh MKT2','Sơn',3),
  m('15','Vân','Jujutsu Kaisen Playing card','Derek Parker','Kênh MKT2','Sao',3),
  m('15','Sơn','Dungeon Crawler card skin','Derek Parker','Kênh MKT4','Sao',3,'Card Skin'),
  m('15','Sơn','Ghost face Playing cards','Chris Rogers','Kênh MKT3','Thư',3),
  m('15','Sơn','Horror HLW Playing card','Jacueline Johnson','Kênh Chính','Vân',3),
  m('15','Sơn','Horror HLW Playing card','Jacueline Johnson','Kênh MKT4','Vân',2),
  m('15','Lan','Resident Evil Playing card (mẫu màu cũ)','Jason Miklian','MKT2','Thu',4),
  m('15','Lan','Red Dead playing card','Jason Miklian','MKT2','Thu',2),
  m('15','Lan','nier: automata PLC','Justin Crosmun','Kênh MKT2','Lan',2),
  m('15','Lan','Scream Ghostface Playing card','Chris Rogers','Kênh MKT4','Thư',3),
  m('15','Lan','nier: automata PLC','Justin Crosmun','Kênh MKT1','Lan',3),
  m('15','Lan','nier: automata PLC','Justin Crosmun','Kênh Chính','Lan',3),
  s('15','Thu','Research ảnh + gen mẫu Fourth Wing','Tiktok US'),
  s('15','Thu','thêm bộ Halloween PLC vào listing kênh','Chris Rogers'),
  s('15','Thu','up 10 listing spam Fourth Wing','Cindy Buban'),
  s('15','Thu','sửa giá up spam HLW doormat & card','David Baker'),
  s('15','Thu','Check trạng thái đơn sắp shiplate: shop','Tiktok US'),
  s('15','Thu','Xoá listing Tattoo','Jason Miklian / James Lawrence'),
  s('15','Thu','• Soạn đơn clone CMS • Tạo Flash sale','Tiktok US'),
  s('15','Sao','Up spam 20 lst wpaper (Gothic HLW)','lucksigns69'),
  s('15','Sao','Up spam 20 lst wpaper (Gothic HLW)','Aaron Macinnis',undefined,undefined,undefined,'Wrapping Paper'),
  s('15','Sao','Soạn đơn (UK), add tracking, đổi SKU'),
  s('15','Sao','Check rf, review 5shop'),
  s('15','Phụng','Check shop health, review, refund','Jason Miklian / Nephtali Gonzalez'),
  s('15','Phụng','Add tracking, support KH, import đơn','lucksigns69'),
  s('15','Phụng','RE Playing card','Jason Miklian','Kênh Chính - annepherson','Phụng',3,'Playing Card'),
  s('15','Phụng','RDR2 Playing cards','Jason Miklian','Kênh Chính - annepherson','Phụng',2,'Playing Card'),
  s('15','Phụng','RE Playing cards','Jason Miklian','Kênh MKT3 - latricialsmith','Phụng',3,'Playing Card'),
  s('15','Phụng','Hollow Knight Playing cards','Jason Miklian','Kênh MKT3 - latricialsmith','Phụng',2,'Playing Card'),
];
async function main(){
  const team=await sql.query(`SELECT id FROM teams WHERE code='kd2'`);if(!team[0])throw new Error('Không tìm thấy KD2.');const teamId=team[0].id as number;
  const cats=await sql.query(`SELECT id,name FROM team_task_categories WHERE team_id=$1 AND name=ANY($2::text[])`,[teamId,['Media','Support']]);const categoryIds=new Map(cats.map(r=>[String(r.name),r.id as number]));if(!categoryIds.has('Media')||!categoryIds.has('Support'))throw new Error('KD2 thiếu nhóm Media hoặc Support.');
  const usernames=[...new Set(tasks.map(t=>t.assignee))];const members=await sql.query(`SELECT u.id,u.username FROM team_members tm JOIN users u ON u.id=tm.user_id WHERE tm.team_id=$1 AND u.username=ANY($2::text[])`,[teamId,usernames]);const memberIds=new Map(members.map(r=>[String(r.username),r.id as number]));const missing=usernames.filter(u=>!memberIds.has(u));if(missing.length)throw new Error(`Thiếu thành viên: ${missing.join(', ')}`);
  const manager=await sql.query(`SELECT user_id FROM team_members WHERE team_id=$1 AND role='manager' ORDER BY user_id LIMIT 1`,[teamId]);const createdBy=(manager[0]?.user_id as number|undefined)??null;let created=0,skipped=0;
  for(const t of tasks){const values=[teamId,categoryIds.get(t.category),t.date,memberIds.get(t.assignee),t.account??null,t.title,t.uploader??null,t.videos??null,t.product??null,t.sourceChannel?`Kênh: ${t.sourceChannel}`:null,createdBy];const rows=await sql.query(`INSERT INTO tasks(team_id,category_id,task_date,assignee_user_id,account_name,title,channel,video_count,product,note,status,created_by) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'done',$11 WHERE NOT EXISTS(SELECT 1 FROM tasks WHERE team_id=$1 AND category_id=$2 AND task_date=$3 AND assignee_user_id=$4 AND account_name IS NOT DISTINCT FROM $5::text AND title=$6 AND channel IS NOT DISTINCT FROM $7::text AND video_count IS NOT DISTINCT FROM $8::integer AND product IS NOT DISTINCT FROM $9::text AND note IS NOT DISTINCT FROM $10::text) RETURNING id`,values);if(rows.length)created++;else skipped++;}
  console.log(`KD2 13-15/08/2026: tạo ${created}, bỏ qua ${skipped} task đã tồn tại.`);
}main().catch(e=>{console.error(e);process.exit(1)});
